/**
 * ============================================
 * QUEUE AGENT - TEMPLATES
 * ============================================
 * Code templates for queue operations including BullMQ queues,
 * workers, processors, schedulers, and monitoring.
 */

// ============================================
// BULLMQ QUEUE TEMPLATES
// ============================================

export const BULLMQ_QUEUE_CONFIG_TEMPLATE = `/**
 * BullMQ Queue Configuration
 * Generated by Queue Agent
 */

import { Queue, QueueOptions } from 'bullmq';

// Redis connection configuration
const redisConnection = {
    host: process.env.REDIS_HOST || 'localhost',
    port: parseInt(process.env.REDIS_PORT || '6379'),
    password: process.env.REDIS_PASSWORD,
    maxRetriesPerRequest: null,
};

// Default queue options
const defaultQueueOptions: QueueOptions = {
    connection: redisConnection,
    defaultJobOptions: {
        attempts: {{MAX_ATTEMPTS}},
        backoff: {
            type: '{{BACKOFF_TYPE}}',
            delay: {{BACKOFF_DELAY}},
        },
        removeOnComplete: {{REMOVE_ON_COMPLETE}},
        removeOnFail: {{REMOVE_ON_FAIL}},
    },
};

// Create queue instance
export const {{QUEUE_NAME_CAMEL}}Queue = new Queue('{{QUEUE_NAME}}', defaultQueueOptions);

// Queue event handlers
{{QUEUE_NAME_CAMEL}}Queue.on('error', (error) => {
    console.error(\`[Queue Error] {{QUEUE_NAME}}:\`, error);
});

export default {{QUEUE_NAME_CAMEL}}Queue;
`;

export const BULLMQ_QUEUE_SETUP_TEMPLATE = `/**
 * Queue Setup & Connection
 * Centralized queue management
 */

import { Queue, Worker, QueueScheduler, QueueEvents } from 'bullmq';
import Redis from 'ioredis';

// Shared Redis connection
export const createRedisConnection = () => {
    return new Redis({
        host: process.env.REDIS_HOST || 'localhost',
        port: parseInt(process.env.REDIS_PORT || '6379'),
        password: process.env.REDIS_PASSWORD,
        maxRetriesPerRequest: null,
        enableReadyCheck: false,
        retryStrategy: (times: number) => {
            const delay = Math.min(times * 50, 2000);
            console.log(\`[Redis] Retry attempt \${times}, waiting \${delay}ms\`);
            return delay;
        },
    });
};

// Queue registry
const queues: Map<string, Queue> = new Map();
const workers: Map<string, Worker> = new Map();
const schedulers: Map<string, QueueScheduler> = new Map();

/**
 * Get or create a queue instance
 */
export function getQueue(name: string): Queue {
    if (!queues.has(name)) {
        const queue = new Queue(name, {
            connection: createRedisConnection(),
        });
        queues.set(name, queue);
    }
    return queues.get(name)!;
}

/**
 * Register a worker for a queue
 */
export function registerWorker(name: string, worker: Worker): void {
    workers.set(name, worker);
}

/**
 * Graceful shutdown of all queues and workers
 */
export async function shutdownQueues(): Promise<void> {
    console.log('[Queue] Shutting down all queues and workers...');
    
    // Close all workers
    for (const [name, worker] of workers) {
        console.log(\`[Queue] Closing worker: \${name}\`);
        await worker.close();
    }
    
    // Close all schedulers
    for (const [name, scheduler] of schedulers) {
        console.log(\`[Queue] Closing scheduler: \${name}\`);
        await scheduler.close();
    }
    
    // Close all queues
    for (const [name, queue] of queues) {
        console.log(\`[Queue] Closing queue: \${name}\`);
        await queue.close();
    }
    
    console.log('[Queue] All queues shut down successfully');
}

// Handle process signals
process.on('SIGTERM', async () => {
    await shutdownQueues();
    process.exit(0);
});

process.on('SIGINT', async () => {
    await shutdownQueues();
    process.exit(0);
});
`;

// ============================================
// WORKER TEMPLATES
// ============================================

export const BULLMQ_WORKER_TEMPLATE = `/**
 * {{WORKER_NAME}} Worker
 * Processes jobs from the {{QUEUE_NAME}} queue
 */

import { Worker, Job } from 'bullmq';
import { createRedisConnection } from './queue-setup';

// Job data type
interface {{JOB_TYPE_NAME}}Data {
    {{JOB_DATA_FIELDS}}
}

// Job result type
interface {{JOB_TYPE_NAME}}Result {
    success: boolean;
    data?: unknown;
    error?: string;
}

/**
 * Process {{JOB_TYPE_NAME}} jobs
 */
async function process{{JOB_TYPE_NAME}}(job: Job<{{JOB_TYPE_NAME}}Data>): Promise<{{JOB_TYPE_NAME}}Result> {
    console.log(\`[Worker] Processing job \${job.id}: \${job.name}\`);
    
    try {
        // Update progress
        await job.updateProgress(10);
        
        // TODO: Implement your job logic here
        const { {{JOB_DATA_DESTRUCTURE}} } = job.data;
        
        await job.updateProgress(50);
        
        // Simulate processing
        // Replace with actual business logic
        console.log(\`[Worker] Job \${job.id} data:\`, job.data);
        
        await job.updateProgress(100);
        
        return {
            success: true,
            data: { processedAt: new Date().toISOString() },
        };
    } catch (error) {
        console.error(\`[Worker] Job \${job.id} failed:\`, error);
        throw error;
    }
}

// Create worker instance
export const {{WORKER_NAME_CAMEL}}Worker = new Worker(
    '{{QUEUE_NAME}}',
    process{{JOB_TYPE_NAME}},
    {
        connection: createRedisConnection(),
        concurrency: {{CONCURRENCY}},
        limiter: {
            max: {{RATE_LIMIT_MAX}},
            duration: {{RATE_LIMIT_DURATION}},
        },
    }
);

// Worker event handlers
{{WORKER_NAME_CAMEL}}Worker.on('completed', (job) => {
    console.log(\`[Worker] Job \${job.id} completed successfully\`);
});

{{WORKER_NAME_CAMEL}}Worker.on('failed', (job, error) => {
    console.error(\`[Worker] Job \${job?.id} failed:\`, error.message);
});

{{WORKER_NAME_CAMEL}}Worker.on('error', (error) => {
    console.error('[Worker] Error:', error);
});

{{WORKER_NAME_CAMEL}}Worker.on('stalled', (jobId) => {
    console.warn(\`[Worker] Job \${jobId} has stalled\`);
});

export default {{WORKER_NAME_CAMEL}}Worker;
`;

export const WORKER_PROCESSOR_TEMPLATE = `/**
 * Job Processor Functions
 * Centralized job processing logic
 */

import { Job } from 'bullmq';

/**
 * Base processor interface
 */
export interface JobProcessor<TData, TResult> {
    name: string;
    process: (job: Job<TData>) => Promise<TResult>;
    onCompleted?: (job: Job<TData>, result: TResult) => void;
    onFailed?: (job: Job<TData>, error: Error) => void;
}

/**
 * Create a typed job processor
 */
export function createProcessor<TData, TResult>(
    name: string,
    handler: (job: Job<TData>) => Promise<TResult>,
    options?: {
        onCompleted?: (job: Job<TData>, result: TResult) => void;
        onFailed?: (job: Job<TData>, error: Error) => void;
    }
): JobProcessor<TData, TResult> {
    return {
        name,
        process: handler,
        onCompleted: options?.onCompleted,
        onFailed: options?.onFailed,
    };
}

// ============================================
// Example Processors
// ============================================

{{PROCESSOR_DEFINITIONS}}
`;

// ============================================
// JOB TYPE TEMPLATES
// ============================================

export const JOB_TYPES_TEMPLATE = `/**
 * Queue Job Type Definitions
 * Type-safe job definitions for all queues
 */

// ============================================
// Base Types
// ============================================

export interface BaseJobData {
    correlationId?: string;
    createdAt?: string;
    userId?: string;
}

export interface BaseJobResult {
    success: boolean;
    processedAt: string;
    error?: string;
}

// ============================================
// Queue Job Types
// ============================================

{{JOB_TYPE_DEFINITIONS}}

// ============================================
// Job Names Registry
// ============================================

export const JOB_NAMES = {
{{JOB_NAMES}}
} as const;

export type JobName = typeof JOB_NAMES[keyof typeof JOB_NAMES];

// ============================================
// Queue Names Registry
// ============================================

export const QUEUE_NAMES = {
{{QUEUE_NAMES}}
} as const;

export type QueueName = typeof QUEUE_NAMES[keyof typeof QUEUE_NAMES];
`;

// ============================================
// RETRY LOGIC TEMPLATES
// ============================================

export const RETRY_STRATEGY_TEMPLATE = `/**
 * Custom Retry Strategies
 * Flexible retry logic for different job types
 */

import { BackoffOptions } from 'bullmq';

// ============================================
// Retry Strategy Types
// ============================================

export type RetryStrategyType = 'fixed' | 'exponential' | 'linear' | 'custom';

export interface RetryConfig {
    strategy: RetryStrategyType;
    maxAttempts: number;
    initialDelay: number;
    maxDelay?: number;
    factor?: number;
    customDelays?: number[];
}

// ============================================
// Predefined Retry Strategies
// ============================================

/**
 * Fixed delay retry - same delay between all attempts
 */
export const FIXED_RETRY: RetryConfig = {
    strategy: 'fixed',
    maxAttempts: 3,
    initialDelay: 1000,
};

/**
 * Exponential backoff - delay doubles each attempt
 */
export const EXPONENTIAL_RETRY: RetryConfig = {
    strategy: 'exponential',
    maxAttempts: 5,
    initialDelay: 1000,
    maxDelay: 60000,
    factor: 2,
};

/**
 * Linear backoff - delay increases linearly
 */
export const LINEAR_RETRY: RetryConfig = {
    strategy: 'linear',
    maxAttempts: 5,
    initialDelay: 1000,
    maxDelay: 30000,
    factor: 1.5,
};

/**
 * Fast retry for transient errors
 */
export const FAST_RETRY: RetryConfig = {
    strategy: 'fixed',
    maxAttempts: 3,
    initialDelay: 100,
};

/**
 * Slow retry for rate limiting
 */
export const RATE_LIMIT_RETRY: RetryConfig = {
    strategy: 'exponential',
    maxAttempts: 10,
    initialDelay: 5000,
    maxDelay: 300000,
    factor: 2,
};

// ============================================
// Retry Helper Functions
// ============================================

/**
 * Calculate delay for a given attempt
 */
export function calculateDelay(config: RetryConfig, attempt: number): number {
    const { strategy, initialDelay, maxDelay = Infinity, factor = 2 } = config;
    
    let delay: number;
    
    switch (strategy) {
        case 'fixed':
            delay = initialDelay;
            break;
        case 'exponential':
            delay = initialDelay * Math.pow(factor, attempt - 1);
            break;
        case 'linear':
            delay = initialDelay * attempt * (factor || 1);
            break;
        case 'custom':
            delay = config.customDelays?.[attempt - 1] || initialDelay;
            break;
        default:
            delay = initialDelay;
    }
    
    return Math.min(delay, maxDelay);
}

/**
 * Convert RetryConfig to BullMQ BackoffOptions
 */
export function toBackoffOptions(config: RetryConfig): BackoffOptions {
    switch (config.strategy) {
        case 'exponential':
            return {
                type: 'exponential',
                delay: config.initialDelay,
            };
        case 'fixed':
        default:
            return {
                type: 'fixed',
                delay: config.initialDelay,
            };
    }
}

/**
 * Should retry based on error type
 */
export function shouldRetry(error: Error): boolean {
    // Retry on transient errors
    const retryableErrors = [
        'ECONNREFUSED',
        'ETIMEDOUT',
        'EHOSTUNREACH',
        'ENETUNREACH',
        'ECONNRESET',
        'EPIPE',
    ];
    
    const errorCode = (error as NodeJS.ErrnoException).code;
    if (errorCode && retryableErrors.includes(errorCode)) {
        return true;
    }
    
    // Retry on rate limit errors
    if (error.message.includes('rate limit') || error.message.includes('429')) {
        return true;
    }
    
    // Don't retry on validation errors
    if (error.message.includes('validation') || error.message.includes('invalid')) {
        return false;
    }
    
    return true;
}
`;

// ============================================
// DEAD LETTER QUEUE TEMPLATES
// ============================================

export const DEAD_LETTER_QUEUE_TEMPLATE = `/**
 * Dead Letter Queue (DLQ) Handler
 * Captures and processes failed jobs
 */

import { Queue, Worker, Job } from 'bullmq';
import { createRedisConnection } from './queue-setup';

// Dead Letter Queue name
const DLQ_NAME = '{{DLQ_NAME}}';

// Create DLQ instance
export const deadLetterQueue = new Queue(DLQ_NAME, {
    connection: createRedisConnection(),
    defaultJobOptions: {
        removeOnComplete: false,
        removeOnFail: false,
    },
});

/**
 * Move a failed job to DLQ
 */
export async function moveToDeadLetterQueue(
    originalJob: Job,
    error: Error,
    queueName: string
): Promise<void> {
    await deadLetterQueue.add('failed-job', {
        originalJobId: originalJob.id,
        originalJobName: originalJob.name,
        originalQueueName: queueName,
        originalData: originalJob.data,
        error: {
            message: error.message,
            stack: error.stack,
            name: error.name,
        },
        failedAt: new Date().toISOString(),
        attemptsMade: originalJob.attemptsMade,
    });
    
    console.log(\`[DLQ] Job \${originalJob.id} moved to dead letter queue\`);
}

/**
 * DLQ Worker - processes failed jobs for analysis
 */
export const dlqWorker = new Worker(
    DLQ_NAME,
    async (job) => {
        console.log(\`[DLQ] Analyzing failed job: \${job.data.originalJobId}\`);
        
        // Log failure details
        console.log({
            jobId: job.data.originalJobId,
            queue: job.data.originalQueueName,
            error: job.data.error.message,
            attempts: job.data.attemptsMade,
            failedAt: job.data.failedAt,
        });
        
        // TODO: Implement alerting, metrics, or auto-recovery
        
        return { analyzed: true };
    },
    {
        connection: createRedisConnection(),
        concurrency: 1,
    }
);

/**
 * Get DLQ statistics
 */
export async function getDLQStats(): Promise<{
    total: number;
    byQueue: Record<string, number>;
    byError: Record<string, number>;
}> {
    const jobs = await deadLetterQueue.getJobs(['waiting', 'completed']);
    
    const byQueue: Record<string, number> = {};
    const byError: Record<string, number> = {};
    
    for (const job of jobs) {
        const queue = job.data.originalQueueName;
        const errorMsg = job.data.error?.message || 'Unknown error';
        
        byQueue[queue] = (byQueue[queue] || 0) + 1;
        byError[errorMsg] = (byError[errorMsg] || 0) + 1;
    }
    
    return {
        total: jobs.length,
        byQueue,
        byError,
    };
}

/**
 * Retry a job from DLQ
 */
export async function retryFromDLQ(
    dlqJobId: string,
    getOriginalQueue: (name: string) => Queue
): Promise<boolean> {
    const job = await deadLetterQueue.getJob(dlqJobId);
    if (!job) {
        throw new Error(\`DLQ job \${dlqJobId} not found\`);
    }
    
    const originalQueue = getOriginalQueue(job.data.originalQueueName);
    
    await originalQueue.add(job.data.originalJobName, job.data.originalData);
    await job.remove();
    
    console.log(\`[DLQ] Job \${dlqJobId} retried to \${job.data.originalQueueName}\`);
    return true;
}
`;

// ============================================
// SCHEDULER TEMPLATES
// ============================================

export const JOB_SCHEDULER_TEMPLATE = `/**
 * Job Scheduler
 * Cron-based job scheduling with BullMQ
 */

import { Queue } from 'bullmq';
import { createRedisConnection } from './queue-setup';

// ============================================
// Scheduled Jobs Configuration
// ============================================

export interface ScheduledJobConfig {
    name: string;
    queueName: string;
    pattern: string;  // Cron pattern
    data?: Record<string, unknown>;
    tz?: string;
    description?: string;
}

// Scheduled jobs registry
const scheduledJobs: ScheduledJobConfig[] = [
{{SCHEDULED_JOBS}}
];

// ============================================
// Scheduler Functions
// ============================================

/**
 * Initialize all scheduled jobs
 */
export async function initializeScheduler(
    queues: Map<string, Queue>
): Promise<void> {
    console.log('[Scheduler] Initializing scheduled jobs...');
    
    for (const job of scheduledJobs) {
        const queue = queues.get(job.queueName);
        if (!queue) {
            console.warn(\`[Scheduler] Queue \${job.queueName} not found for job \${job.name}\`);
            continue;
        }
        
        // Add repeatable job
        await queue.add(
            job.name,
            job.data || {},
            {
                repeat: {
                    pattern: job.pattern,
                    tz: job.tz || 'UTC',
                },
            }
        );
        
        console.log(\`[Scheduler] Scheduled job: \${job.name} (\${job.pattern})\`);
    }
    
    console.log(\`[Scheduler] Initialized \${scheduledJobs.length} scheduled jobs\`);
}

/**
 * Remove a scheduled job
 */
export async function removeScheduledJob(
    queue: Queue,
    jobName: string
): Promise<boolean> {
    const repeatableJobs = await queue.getRepeatableJobs();
    const job = repeatableJobs.find(j => j.name === jobName);
    
    if (job) {
        await queue.removeRepeatableByKey(job.key);
        console.log(\`[Scheduler] Removed scheduled job: \${jobName}\`);
        return true;
    }
    
    return false;
}

/**
 * List all scheduled jobs
 */
export async function listScheduledJobs(
    queue: Queue
): Promise<ScheduledJobConfig[]> {
    const repeatableJobs = await queue.getRepeatableJobs();
    
    return repeatableJobs.map(job => ({
        name: job.name || 'unnamed',
        queueName: queue.name,
        pattern: job.pattern || '',
        tz: job.tz,
    }));
}

/**
 * Update scheduled job pattern
 */
export async function updateScheduledJob(
    queue: Queue,
    jobName: string,
    newPattern: string,
    newData?: Record<string, unknown>
): Promise<boolean> {
    // Remove old job
    const removed = await removeScheduledJob(queue, jobName);
    if (!removed) return false;
    
    // Add new job with updated pattern
    await queue.add(
        jobName,
        newData || {},
        {
            repeat: {
                pattern: newPattern,
            },
        }
    );
    
    console.log(\`[Scheduler] Updated job \${jobName} to pattern: \${newPattern}\`);
    return true;
}
`;

// ============================================
// QUEUE MONITORING TEMPLATES
// ============================================

export const QUEUE_MONITORING_TEMPLATE = `/**
 * Queue Monitoring & Metrics
 * Health checks and performance monitoring
 */

import { Queue, QueueEvents } from 'bullmq';
import { createRedisConnection } from './queue-setup';

// ============================================
// Queue Metrics Collection
// ============================================

export interface QueueMetrics {
    queueName: string;
    waiting: number;
    active: number;
    completed: number;
    failed: number;
    delayed: number;
    paused: boolean;
    timestamp: Date;
}

/**
 * Get metrics for a single queue
 */
export async function getQueueMetrics(queue: Queue): Promise<QueueMetrics> {
    const [waiting, active, completed, failed, delayed, paused] = await Promise.all([
        queue.getWaitingCount(),
        queue.getActiveCount(),
        queue.getCompletedCount(),
        queue.getFailedCount(),
        queue.getDelayedCount(),
        queue.isPaused(),
    ]);
    
    return {
        queueName: queue.name,
        waiting,
        active,
        completed,
        failed,
        delayed,
        paused,
        timestamp: new Date(),
    };
}

/**
 * Get metrics for all queues
 */
export async function getAllQueueMetrics(
    queues: Map<string, Queue>
): Promise<QueueMetrics[]> {
    const metrics: QueueMetrics[] = [];
    
    for (const [_, queue] of queues) {
        metrics.push(await getQueueMetrics(queue));
    }
    
    return metrics;
}

// ============================================
// Queue Health Checks
// ============================================

export interface QueueHealthStatus {
    healthy: boolean;
    queueName: string;
    status: 'ok' | 'warning' | 'critical';
    message: string;
    metrics: QueueMetrics;
}

export interface HealthThresholds {
    maxWaiting: number;
    maxFailed: number;
    maxDelayed: number;
}

const DEFAULT_THRESHOLDS: HealthThresholds = {
    maxWaiting: 1000,
    maxFailed: 100,
    maxDelayed: 500,
};

/**
 * Check health of a queue
 */
export async function checkQueueHealth(
    queue: Queue,
    thresholds: HealthThresholds = DEFAULT_THRESHOLDS
): Promise<QueueHealthStatus> {
    const metrics = await getQueueMetrics(queue);
    
    let status: 'ok' | 'warning' | 'critical' = 'ok';
    let message = 'Queue is healthy';
    
    // Check for issues
    if (metrics.failed > thresholds.maxFailed) {
        status = 'critical';
        message = \`High failure rate: \${metrics.failed} failed jobs\`;
    } else if (metrics.waiting > thresholds.maxWaiting) {
        status = 'warning';
        message = \`Queue backlog: \${metrics.waiting} waiting jobs\`;
    } else if (metrics.delayed > thresholds.maxDelayed) {
        status = 'warning';
        message = \`Many delayed jobs: \${metrics.delayed}\`;
    } else if (metrics.paused) {
        status = 'warning';
        message = 'Queue is paused';
    }
    
    return {
        healthy: status !== 'critical',
        queueName: queue.name,
        status,
        message,
        metrics,
    };
}

// ============================================
// Queue Events Listener
// ============================================

/**
 * Create a queue events listener
 */
export function createQueueEventsListener(
    queueName: string,
    handlers: {
        onCompleted?: (jobId: string, result: unknown) => void;
        onFailed?: (jobId: string, error: Error) => void;
        onProgress?: (jobId: string, progress: number) => void;
        onStalled?: (jobId: string) => void;
    }
): QueueEvents {
    const queueEvents = new QueueEvents(queueName, {
        connection: createRedisConnection(),
    });
    
    if (handlers.onCompleted) {
        queueEvents.on('completed', ({ jobId, returnvalue }) => {
            handlers.onCompleted!(jobId, returnvalue);
        });
    }
    
    if (handlers.onFailed) {
        queueEvents.on('failed', ({ jobId, failedReason }) => {
            handlers.onFailed!(jobId, new Error(failedReason));
        });
    }
    
    if (handlers.onProgress) {
        queueEvents.on('progress', ({ jobId, data }) => {
            handlers.onProgress!(jobId, data as number);
        });
    }
    
    if (handlers.onStalled) {
        queueEvents.on('stalled', ({ jobId }) => {
            handlers.onStalled!(jobId);
        });
    }
    
    return queueEvents;
}

// ============================================
// Metrics Exporter (Prometheus-compatible)
// ============================================

/**
 * Export metrics in Prometheus format
 */
export async function exportPrometheusMetrics(
    queues: Map<string, Queue>
): Promise<string> {
    const allMetrics = await getAllQueueMetrics(queues);
    let output = '';
    
    output += '# HELP queue_waiting_jobs Number of jobs waiting in queue\\n';
    output += '# TYPE queue_waiting_jobs gauge\\n';
    for (const m of allMetrics) {
        output += \`queue_waiting_jobs{queue="\${m.queueName}"} \${m.waiting}\\n\`;
    }
    
    output += '# HELP queue_active_jobs Number of active jobs\\n';
    output += '# TYPE queue_active_jobs gauge\\n';
    for (const m of allMetrics) {
        output += \`queue_active_jobs{queue="\${m.queueName}"} \${m.active}\\n\`;
    }
    
    output += '# HELP queue_completed_jobs_total Total completed jobs\\n';
    output += '# TYPE queue_completed_jobs_total counter\\n';
    for (const m of allMetrics) {
        output += \`queue_completed_jobs_total{queue="\${m.queueName}"} \${m.completed}\\n\`;
    }
    
    output += '# HELP queue_failed_jobs_total Total failed jobs\\n';
    output += '# TYPE queue_failed_jobs_total counter\\n';
    for (const m of allMetrics) {
        output += \`queue_failed_jobs_total{queue="\${m.queueName}"} \${m.failed}\\n\`;
    }
    
    return output;
}
`;

// ============================================
// JOB FLOW TEMPLATES
// ============================================

export const JOB_FLOW_TEMPLATE = `/**
 * Job Flows & Dependencies
 * Complex job workflows with parent-child relationships
 */

import { FlowProducer, Queue, FlowJob } from 'bullmq';
import { createRedisConnection } from './queue-setup';

// Create flow producer
export const flowProducer = new FlowProducer({
    connection: createRedisConnection(),
});

/**
 * Flow definition type
 */
export interface FlowDefinition {
    name: string;
    queueName: string;
    data: Record<string, unknown>;
    children?: FlowDefinition[];
    opts?: {
        priority?: number;
        delay?: number;
        attempts?: number;
    };
}

/**
 * Convert flow definition to BullMQ FlowJob
 */
function toFlowJob(flow: FlowDefinition): FlowJob {
    return {
        name: flow.name,
        queueName: flow.queueName,
        data: flow.data,
        children: flow.children?.map(toFlowJob),
        opts: flow.opts,
    };
}

/**
 * Create a job flow
 */
export async function createFlow(flow: FlowDefinition): Promise<string> {
    const result = await flowProducer.add(toFlowJob(flow));
    console.log(\`[Flow] Created flow: \${flow.name} with root job \${result.job.id}\`);
    return result.job.id!;
}

// ============================================
// Predefined Flow Templates
// ============================================

{{FLOW_DEFINITIONS}}

/**
 * Execute a predefined flow by name
 */
export async function executeFlow(
    flowName: string,
    data: Record<string, unknown>
): Promise<string> {
    switch (flowName) {
        // Add cases for predefined flows
        default:
            throw new Error(\`Unknown flow: \${flowName}\`);
    }
}
`;

// ============================================
// RATE LIMITING TEMPLATES
// ============================================

export const RATE_LIMITER_TEMPLATE = `/**
 * Queue Rate Limiting
 * Control job processing rates
 */

import { Queue, Worker } from 'bullmq';

// ============================================
// Rate Limit Configurations
// ============================================

export interface RateLimitConfig {
    max: number;       // Maximum jobs
    duration: number;  // Time window in ms
    groupKey?: string; // Optional grouping key
}

// Predefined rate limits
export const RATE_LIMITS = {
    // Standard limits
    LOW: { max: 10, duration: 1000 },
    NORMAL: { max: 50, duration: 1000 },
    HIGH: { max: 100, duration: 1000 },
    
    // API-friendly limits to avoid rate limiting
    EXTERNAL_API: { max: 5, duration: 1000 },
    EMAIL: { max: 30, duration: 60000 },  // 30 emails per minute
    SMS: { max: 10, duration: 60000 },    // 10 SMS per minute
    
    // Batch processing
    BATCH: { max: 1000, duration: 60000 },
} as const;

/**
 * Create a rate-limited worker
 */
export function createRateLimitedWorker<TData, TResult>(
    queueName: string,
    processor: (job: { data: TData }) => Promise<TResult>,
    rateLimit: RateLimitConfig,
    concurrency: number = 1
): Worker<TData, TResult> {
    return new Worker<TData, TResult>(
        queueName,
        async (job) => processor(job),
        {
            concurrency,
            limiter: {
                max: rateLimit.max,
                duration: rateLimit.duration,
                groupKey: rateLimit.groupKey,
            },
        }
    );
}

/**
 * Dynamic rate limiting based on queue state
 */
export async function adjustRateLimit(
    queue: Queue,
    worker: Worker,
    thresholds: {
        highWaterMark: number;
        lowWaterMark: number;
        highLimit: RateLimitConfig;
        lowLimit: RateLimitConfig;
    }
): Promise<RateLimitConfig> {
    const waitingCount = await queue.getWaitingCount();
    
    if (waitingCount > thresholds.highWaterMark) {
        // Speed up processing
        await worker.rateLimit(thresholds.highLimit.max, thresholds.highLimit.duration);
        console.log(\`[RateLimit] Increased rate for \${queue.name}: \${thresholds.highLimit.max}/\${thresholds.highLimit.duration}ms\`);
        return thresholds.highLimit;
    } else if (waitingCount < thresholds.lowWaterMark) {
        // Slow down processing
        await worker.rateLimit(thresholds.lowLimit.max, thresholds.lowLimit.duration);
        console.log(\`[RateLimit] Decreased rate for \${queue.name}: \${thresholds.lowLimit.max}/\${thresholds.lowLimit.duration}ms\`);
        return thresholds.lowLimit;
    }
    
    return { max: 0, duration: 0 }; // No change
}
`;

// ============================================
// TEMPLATE TYPE DEFINITIONS
// ============================================

export type QueueTemplateType =
    | 'queue-config'
    | 'queue-setup'
    | 'worker'
    | 'processor'
    | 'job-types'
    | 'retry-strategy'
    | 'dead-letter-queue'
    | 'scheduler'
    | 'monitoring'
    | 'flow'
    | 'rate-limiter';

// ============================================
// TEMPLATE SETS
// ============================================

export const QUEUE_TEMPLATE_SETS = {
    basic: ['queue-config', 'worker', 'job-types'],
    standard: ['queue-config', 'queue-setup', 'worker', 'processor', 'job-types', 'retry-strategy'],
    advanced: ['queue-config', 'queue-setup', 'worker', 'processor', 'job-types', 'retry-strategy', 'dead-letter-queue', 'monitoring'],
    enterprise: ['queue-config', 'queue-setup', 'worker', 'processor', 'job-types', 'retry-strategy', 'dead-letter-queue', 'scheduler', 'monitoring', 'flow', 'rate-limiter'],
} as const;

// ============================================
// TEMPLATE UTILITIES
// ============================================

/**
 * Get all available templates
 */
export function getAvailableTemplates(): string[] {
    return [
        'queue-config',
        'queue-setup',
        'worker',
        'processor',
        'job-types',
        'retry-strategy',
        'dead-letter-queue',
        'scheduler',
        'monitoring',
        'flow',
        'rate-limiter',
    ];
}

/**
 * Get template by type
 */
export function getTemplate(type: QueueTemplateType): string {
    switch (type) {
        case 'queue-config':
            return BULLMQ_QUEUE_CONFIG_TEMPLATE;
        case 'queue-setup':
            return BULLMQ_QUEUE_SETUP_TEMPLATE;
        case 'worker':
            return BULLMQ_WORKER_TEMPLATE;
        case 'processor':
            return WORKER_PROCESSOR_TEMPLATE;
        case 'job-types':
            return JOB_TYPES_TEMPLATE;
        case 'retry-strategy':
            return RETRY_STRATEGY_TEMPLATE;
        case 'dead-letter-queue':
            return DEAD_LETTER_QUEUE_TEMPLATE;
        case 'scheduler':
            return JOB_SCHEDULER_TEMPLATE;
        case 'monitoring':
            return QUEUE_MONITORING_TEMPLATE;
        case 'flow':
            return JOB_FLOW_TEMPLATE;
        case 'rate-limiter':
            return RATE_LIMITER_TEMPLATE;
        default:
            throw new Error(`Unknown template type: ${type}`);
    }
}

/**
 * Get templates for a specific use case
 */
export function getQueueTemplates(useCase: keyof typeof QUEUE_TEMPLATE_SETS): string[] {
    return QUEUE_TEMPLATE_SETS[useCase] as unknown as string[];
}

/**
 * Get available use case types
 */
export function getAvailableQueueTypes(): string[] {
    return Object.keys(QUEUE_TEMPLATE_SETS);
}
