/**
 * Blueprint Enforcer
 * 
 * Ensures all blueprint files are generated by:
 * 1. Verifying completeness - comparing generated files against blueprint
 * 2. Generating missing files from language-specific templates
 * 
 * Problem: AI ignores blueprint and generates incomplete code
 * Solution: Generate missing files from templates, enforce structure
 */

import type { ArchitectureBlueprint } from './architecture-blueprint.js';

export interface GeneratedFile {
    path: string;
    content: string;
    language?: string;
    type?: 'code' | 'config' | 'schema' | 'migration' | 'doc';
}

export interface VerificationResult {
    complete: boolean;
    missing: string[];
    extra: string[];
    generated: GeneratedFile[];
}

export class BlueprintEnforcer {
    /**
     * Verify all blueprint files were generated
     */
    verifyCompleteness(
        blueprint: ArchitectureBlueprint,
        generated: GeneratedFile[]
    ): VerificationResult {
        const generatedPaths = new Set(
            generated.map(f => this.normalizePath(f.path))
        );

        // Extract required paths from blueprint file structure
        const blueprintPaths = new Set(
            blueprint.fileStructure
                .map(f => this.extractPathFromFileLine(f))
                .filter(p => p !== null)
        );

        const missing = [...blueprintPaths].filter(p => !generatedPaths.has(p));
        const extra = [...generatedPaths].filter(p => !blueprintPaths.has(p));

        console.log(`[BLUEPRINT-ENFORCER] Blueprint: ${blueprintPaths.size} files, Generated: ${generatedPaths.size} files`);
        console.log(`[BLUEPRINT-ENFORCER] Missing: ${missing.length}, Extra: ${extra.length}`);

        return {
            complete: missing.length === 0,
            missing,
            extra,
            generated: [],
        };
    }

    /**
     * Generate missing files from templates
     */
    generateMissingFiles(
        missing: string[],
        blueprint: ArchitectureBlueprint,
        language: string,
        framework: string
    ): GeneratedFile[] {
        const files: GeneratedFile[] = [];

        for (const path of missing) {
            const template = this.getTemplateForFile(path, blueprint, language, framework);
            if (template) {
                files.push({
                    path,
                    content: template,
                    language: this.detectLanguage(path),
                    type: this.getFileType(path),
                });
                console.log(`[BLUEPRINT-ENFORCER] Generated missing file: ${path}`);
            }
        }

        return files;
    }

    /**
     * Enforce blueprint - verify and generate missing files
     */
    enforce(
        blueprint: ArchitectureBlueprint,
        generated: GeneratedFile[],
        language: string,
        framework: string
    ): { files: GeneratedFile[]; added: number; verification: VerificationResult } {
        // Verify
        const verification = this.verifyCompleteness(blueprint, generated);

        // Generate missing
        const missingFiles = this.generateMissingFiles(
            verification.missing,
            blueprint,
            language,
            framework
        );

        // Combine
        const allFiles = [...generated, ...missingFiles];

        return {
            files: allFiles,
            added: missingFiles.length,
            verification,
        };
    }

    /**
     * Extract file path from blueprint line (e.g., "📄 app.py" -> "app.py")
     */
    private extractPathFromFileLine(line: string): string | null {
        // Remove emoji and get path
        const match = line.match(/[📄📁]\s*(.+)/);
        if (match) {
            return this.normalizePath(match[1].trim());
        }
        // Try without emoji
        const clean = line.trim();
        if (clean && !clean.startsWith('│') && !clean.startsWith('├') && !clean.startsWith('└')) {
            return this.normalizePath(clean);
        }
        return null;
    }

    /**
     * Normalize path for comparison
     */
    private normalizePath(path: string): string {
        return path
            .replace(/\\/g, '/')
            .toLowerCase()
            .replace(/^src\//, '')
            .trim();
    }

    /**
     * Detect language from file extension
     */
    private detectLanguage(path: string): string {
        const ext = path.substring(path.lastIndexOf('.')).toLowerCase();
        const langMap: Record<string, string> = {
            '.ts': 'typescript',
            '.tsx': 'typescript',
            '.js': 'javascript',
            '.jsx': 'javascript',
            '.py': 'python',
            '.go': 'go',
            '.rs': 'rust',
            '.java': 'java',
            '.kt': 'kotlin',
            '.cs': 'csharp',
            '.rb': 'ruby',
            '.php': 'php',
            '.swift': 'swift',
        };
        return langMap[ext] || 'typescript';
    }

    /**
     * Get file type from path
     */
    private getFileType(path: string): GeneratedFile['type'] {
        const lower = path.toLowerCase();
        if (lower.includes('test') || lower.includes('spec')) return 'code';
        if (lower.includes('migration')) return 'migration';
        if (lower.includes('schema')) return 'schema';
        if (lower.endsWith('.json') || lower.endsWith('.yaml') || lower.endsWith('.yml')) return 'config';
        if (lower.endsWith('.md')) return 'doc';
        return 'code';
    }

    /**
     * Get template content for a file path
     */
    private getTemplateForFile(
        path: string,
        blueprint: ArchitectureBlueprint,
        language: string,
        framework: string
    ): string | null {
        const fileName = path.split('/').pop() || '';
        const lowerPath = path.toLowerCase();

        // Python templates
        if (language === 'python') {
            return this.getPythonTemplate(fileName, lowerPath, framework, blueprint);
        }

        // TypeScript/JavaScript templates
        if (language === 'typescript' || language === 'javascript') {
            return this.getTypeScriptTemplate(fileName, lowerPath, framework, blueprint);
        }

        // Go templates
        if (language === 'go') {
            return this.getGoTemplate(fileName, lowerPath, blueprint);
        }

        // Rust templates
        if (language === 'rust') {
            return this.getRustTemplate(fileName, lowerPath, blueprint);
        }

        return null;
    }

    /**
     * Python file templates
     */
    private getPythonTemplate(
        fileName: string,
        lowerPath: string,
        _framework: string,
        blueprint: ArchitectureBlueprint
    ): string | null {
        // __init__.py files
        if (fileName === '__init__.py') {
            return this.generatePythonInit(lowerPath, blueprint);
        }

        // Middleware files
        if (lowerPath.includes('middleware')) {
            return this.getPythonMiddlewareTemplate(fileName, _framework);
        }

        // Route files
        if (lowerPath.includes('routes/') || lowerPath.includes('route/')) {
            return this.getPythonRouteTemplate(fileName, _framework, blueprint);
        }

        // Service files
        if (lowerPath.includes('services/') || lowerPath.includes('service/')) {
            return this.getPythonServiceTemplate(fileName, _framework);
        }

        // Model files
        if (lowerPath.includes('models/') || lowerPath.includes('model/')) {
            return this.getPythonModelTemplate(fileName, _framework);
        }

        // Config files
        if (fileName === 'config.py' || fileName === 'settings.py') {
            return this.getPythonConfigTemplate(_framework);
        }

        // Requirements
        if (fileName === 'requirements.txt') {
            return this.getPythonRequirements(_framework);
        }

        // .env.example
        if (fileName === '.env.example') {
            return this.getEnvExample();
        }

        return null;
    }

    /**
     * Generate __init__.py content
     */
    private generatePythonInit(lowerPath: string, blueprint: ArchitectureBlueprint): string {
        const parts = lowerPath.split('/');
        const folderName = parts[parts.length - 2] || '';

        // Extract exports based on folder
        let exports = '';

        if (folderName === 'models') {
            exports = blueprint.database.tables
                .map(t => `from .${t.name} import ${this.toPascalCase(t.name)}`)
                .join('\n');
        } else if (folderName === 'routes') {
            exports = blueprint.routes
                .map(r => `from .${r.path.split('/').pop()} import router`)
                .join('\n');
        } else if (folderName === 'services') {
            exports = blueprint.services
                .map(s => `from .${s.name.toLowerCase().replace('service', '')}_service import ${s.name}`)
                .join('\n');
        }

        return `"""
${this.toPascalCase(folderName)} Module
"""

${exports}

__all__ = []
`;
    }

    /**
     * Python middleware template
     */
    private getPythonMiddlewareTemplate(fileName: string, framework: string): string {
        const name = fileName.replace('.py', '').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
        const className = name.replace(/ /g, '');

        if (framework === 'fastapi' || framework === 'flask') {
            return `"""
${className} Middleware
"""

from typing import Callable, Any
from fastapi import Request, Response
import logging

logger = logging.getLogger(__name__)


class ${className}:
    """
    ${className} middleware for request processing
    """
    
    def __init__(self, app: Any):
        self.app = app
    
    async def __call__(self, request: Request, call_next: Callable) -> Response:
        # Pre-processing
        logger.debug(f"${className}: Processing request to {request.url.path}")
        
        # Call next middleware/handler
        response = await call_next(request)
        
        # Post-processing
        return response


def get_${fileName.replace('.py', '')}() -> ${className}:
    """Get middleware instance"""
    return ${className}
`;
        }

        return `"""
${className} Middleware
"""

import logging

logger = logging.getLogger(__name__)


class ${className}:
    """${className} middleware"""
    
    def __init__(self):
        self.initialized = True
    
    def process(self, request: Any) -> Any:
        """Process request"""
        return request


def get_${fileName.replace('.py', '')}() -> ${className}:
    return ${className}()
`;
    }

    /**
     * Python route template
     */
    private getPythonRouteTemplate(fileName: string, framework: string, blueprint: ArchitectureBlueprint): string {
        const routeName = fileName.replace('.py', '').replace(/-/g, '_');
        const className = this.toPascalCase(routeName);

        // Find matching route in blueprint
        const matchingRoutes = blueprint.routes.filter(r =>
            r.path.toLowerCase().includes(routeName.toLowerCase())
        );

        const routeDefs = matchingRoutes.map(r =>
            `@router.${r.method.toLowerCase()}("${r.path.split('/').pop()}")\nasync def ${r.handler}(request: Request):\n    """${r.description}"""\n    return {"success": True}`
        ).join('\n\n');

        if (framework === 'fastapi') {
            return `"""
${className} Routes
"""

from fastapi import APIRouter, Request, Depends
from typing import Any

router = APIRouter()

${routeDefs || `@router.get("/")
async def get_${routeName}():
    """Get ${routeName}"""
    return {"success": True, "data": []}`}


# Export router
__all__ = ["router"]
`;
        }

        return `"""
${className} Routes
"""

router = None  # Placeholder

${routeDefs || 'pass'}
`;
    }

    /**
     * Python service template
     */
    private getPythonServiceTemplate(fileName: string, _framework: string): string {
        const serviceName = fileName.replace('_service.py', '').replace('.py', '');
        const className = this.toPascalCase(serviceName) + 'Service';

        return `"""
${className}
Business logic for ${serviceName} operations
"""

from typing import Any, Dict, List, Optional
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


class ${className}:
    """
    ${className} - Business logic layer
    """
    
    def __init__(self):
        self._initialized = True
        logger.info(f"${className} initialized")
    
    async def create(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Create a new ${serviceName}"""
        logger.info(f"Creating ${serviceName}")
        return {
            "id": "generated-id",
            "created_at": datetime.utcnow().isoformat(),
            **data
        }
    
    async def get_by_id(self, id: str) -> Optional[Dict[str, Any]]:
        """Get ${serviceName} by ID"""
        logger.info(f"Getting ${serviceName}: {id}")
        return None
    
    async def get_all(self, filters: Optional[Dict[str, Any]] = None) -> List[Dict[str, Any]]:
        """Get all ${serviceName}s"""
        logger.info(f"Getting all ${serviceName}s")
        return []
    
    async def update(self, id: str, data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Update ${serviceName}"""
        logger.info(f"Updating ${serviceName}: {id}")
        return {"id": id, **data}
    
    async def delete(self, id: str) -> bool:
        """Delete ${serviceName}"""
        logger.info(f"Deleting ${serviceName}: {id}")
        return True


# Singleton instance
_instance: Optional[${className}] = None


def get_${serviceName}_service() -> ${className}:
    """Get singleton instance"""
    global _instance
    if _instance is None:
        _instance = ${className}()
    return _instance
`;
    }

    /**
     * Python model template
     */
    private getPythonModelTemplate(fileName: string, _framework: string): string {
        const modelName = fileName.replace('.py', '');
        const className = this.toPascalCase(modelName);

        return `"""
${className} Model
Database model for ${modelName}
"""

from datetime import datetime
from typing import Optional
from sqlalchemy import Column, Integer, String, DateTime, Text, Boolean
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class ${className}(Base):
    """${className} database model"""
    __tablename__ = '${modelName}s'
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "is_active": self.is_active,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
`;
    }

    /**
     * Python config template
     */
    private getPythonConfigTemplate(_framework: string): string {
        return `"""
Application Configuration
"""

import os
from typing import List
from pydantic import BaseSettings


class Settings(BaseSettings):
    """Application settings"""
    
    # App
    APP_NAME: str = "Generated API"
    APP_VERSION: str = "1.0.0"
    DEBUG: bool = True
    
    # Server
    HOST: str = "0.0.0.0"
    PORT: int = 8000
    
    # Database
    DATABASE_URL: str = "sqlite:///./app.db"
    
    # Security
    SECRET_KEY: str = "change-this-in-production"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 30
    
    # CORS
    CORS_ORIGINS: List[str] = ["http://localhost:3000"]
    
    class Config:
        env_file = ".env"
        case_sensitive = True


settings = Settings()
`;
    }

    /**
     * Python requirements.txt
     */
    private getPythonRequirements(framework: string): string {
        if (framework === 'fastapi') {
            return `fastapi>=0.100.0
uvicorn[standard]>=0.23.0
sqlalchemy>=2.0.0
pydantic>=2.0.0
python-jose[cryptography]>=3.3.0
passlib[bcrypt]>=1.7.4
python-multipart>=0.0.6
httpx>=0.24.0
`;
        }
        if (framework === 'django') {
            return `django>=4.2
djangorestframework>=3.14
django-cors-headers>=4.2
psycopg2-binary>=2.9
gunicorn>=21.0
`;
        }
        return `flask>=2.3
flask-cors>=4.0
sqlalchemy>=2.0
gunicorn>=21.0
`;
    }

    /**
     * TypeScript file templates
     */
    private getTypeScriptTemplate(
        fileName: string,
        lowerPath: string,
        framework: string,
        blueprint: ArchitectureBlueprint
    ): string | null {
        if (framework === 'nestjs') {
            return this.getNestJSTemplate(fileName, lowerPath, blueprint);
        }

        if (lowerPath.includes('middleware')) {
            return this.getTypeScriptMiddlewareTemplate(fileName, framework);
        }

        if (lowerPath.includes('routes/') || lowerPath.includes('route/')) {
            return this.getTypeScriptRouteTemplate(fileName, framework, blueprint);
        }

        if (lowerPath.includes('services/') || lowerPath.includes('service/')) {
            return this.getTypeScriptServiceTemplate(fileName, framework);
        }

        if (lowerPath.includes('types/') || fileName.endsWith('.d.ts')) {
            return this.getTypeScriptTypesTemplate(blueprint);
        }

        if (fileName === 'env.ts' || fileName === 'config.ts') {
            return this.getTypeScriptConfigTemplate(framework);
        }

        return null;
    }

    /**
     * NestJS templates (CG-007 - Full working templates)
     */
    private getNestJSTemplate(
        fileName: string,
        lowerPath: string,
        blueprint: ArchitectureBlueprint
    ): string | null {
        if (fileName === 'main.ts') {
            return this.getNestJSMainTemplate();
        }

        if (fileName === 'app.module.ts') {
            return this.getNestJSAppModuleTemplate(blueprint);
        }

        if (lowerPath.includes('schema') || lowerPath.includes('schemas/')) {
            const name = fileName.replace('.schema.ts', '').replace('.ts', '');
            return this.getNestJSSchemaTemplate(name);
        }

        if (lowerPath.includes('service')) {
            const name = fileName.replace('.service.ts', '').replace('.ts', '');
            return this.getNestJSServiceTemplate(name);
        }

        if (lowerPath.includes('controller')) {
            const name = fileName.replace('.controller.ts', '').replace('.ts', '');
            return this.getNestJSControllerTemplate(name);
        }

        if (lowerPath.includes('module') && !fileName.includes('app.module')) {
            const name = fileName.replace('.module.ts', '').replace('.ts', '');
            return this.getNestJSModuleTemplate(name);
        }

        if (lowerPath.includes('dto')) {
            const name = fileName.replace('.dto.ts', '').replace('.ts', '');
            return this.getNestJSDtoTemplate(name);
        }

        if (fileName === 'configuration.ts' || fileName === 'config.ts') {
            return this.getNestJSConfigTemplate();
        }

        return null;
    }

    /**
     * NestJS main.ts template
     */
    private getNestJSMainTemplate(): string {
        return `import { NestFactory } from '@nestjs/core';
import { ValidationPipe, Logger } from '@nestjs/common';
import { AppModule } from './app.module';

async function bootstrap() {
    const logger = new Logger('Bootstrap');
    const app = await NestFactory.create(AppModule);

    app.useGlobalPipes(
        new ValidationPipe({
            whitelist: true,
            forbidNonWhitelisted: true,
            transform: true,
        }),
    );

    app.enableCors({
        origin: process.env.CORS_ORIGINS?.split(',') || ['http://localhost:3000'],
        credentials: true,
    });

    const port = process.env.PORT || 3000;
    await app.listen(port);

    logger.log(\`Application is running on: http://localhost:\${port}\`);
}

bootstrap();
`;
    }

    /**
     * NestJS app.module.ts template
     */
    private getNestJSAppModuleTemplate(blueprint: ArchitectureBlueprint): string {
        const modules = blueprint.services.map(s => `${this.toPascalCase(s.name)}Module`).join(',\n        ');
        const moduleImports = blueprint.services.map(s => 
            `import { ${this.toPascalCase(s.name)}Module } from './${s.name.toLowerCase()}/${s.name.toLowerCase()}.module';`
        ).join('\n');

        return `import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { MongooseModule } from '@nestjs/mongoose';
import configuration from './config/configuration';

${moduleImports}

@Module({
    imports: [
        ConfigModule.forRoot({
            isGlobal: true,
            load: [configuration],
        }),
        MongooseModule.forRoot(process.env.MONGODB_URI || 'mongodb://localhost:27017/app'),
        ${modules}
    ],
    controllers: [],
    providers: [],
})
export class AppModule {}
`;
    }

    /**
     * NestJS schema template
     */
    private getNestJSSchemaTemplate(name: string): string {
        const className = this.toPascalCase(name);
        return `import { Schema, Prop, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type ${className}Document = ${className} & Document;

@Schema({ timestamps: true, collection: '${name.toLowerCase()}s' })
export class ${className} {
    @Prop({ required: true })
    name: string;

    @Prop()
    description?: string;

    @Prop({ default: true })
    isActive: boolean;

    @Prop({ type: Date, default: Date.now })
    createdAt: Date;

    @Prop({ type: Date, default: Date.now })
    updatedAt: Date;
}

export const ${className}Schema = SchemaFactory.createForClass(${className});

${className}Schema.index({ name: 1 });
${className}Schema.index({ isActive: 1 });
`;
    }

    /**
     * NestJS service template
     */
    private getNestJSServiceTemplate(name: string): string {
        const className = this.toPascalCase(name);
        return `import { Injectable, NotFoundException, Logger } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { ${className}, ${className}Document } from './schemas/${name.toLowerCase()}.schema';

@Injectable()
export class ${className}Service {
    private readonly logger = new Logger(${className}Service.name);

    constructor(
        @InjectModel(${className}.name) private ${name.toLowerCase()}Model: Model<${className}Document>,
    ) {}

    async create(createDto: Partial<${className}>): Promise<${className}Document> {
        this.logger.log(\`Creating new ${name}\`);
        const created = new this.${name.toLowerCase()}Model(createDto);
        return created.save();
    }

    async findAll(): Promise<${className}Document[]> {
        this.logger.log(\`Finding all ${name}s\`);
        return this.${name.toLowerCase()}Model.find().exec();
    }

    async findById(id: string): Promise<${className}Document | null> {
        if (!Types.ObjectId.isValid(id)) {
            return null;
        }
        return this.${name.toLowerCase()}Model.findById(id).exec();
    }

    async update(id: string, updateDto: Partial<${className}>): Promise<${className}Document | null> {
        if (!Types.ObjectId.isValid(id)) {
            return null;
        }
        return this.${name.toLowerCase()}Model
            .findByIdAndUpdate(id, updateDto, { new: true })
            .exec();
    }

    async delete(id: string): Promise<boolean> {
        if (!Types.ObjectId.isValid(id)) {
            return false;
        }
        const result = await this.${name.toLowerCase()}Model.findByIdAndDelete(id).exec();
        return !!result;
    }
}
`;
    }

    /**
     * NestJS controller template
     */
    private getNestJSControllerTemplate(name: string): string {
        const className = this.toPascalCase(name);
        return `import { Controller, Get, Post, Put, Delete, Body, Param, ParseObjectIdPipe, Logger } from '@nestjs/common';
import { ${className}Service } from './${name.toLowerCase()}.service';
import { ${className} } from './schemas/${name.toLowerCase()}.schema';

@Controller('${name.toLowerCase()}s')
export class ${className}Controller {
    private readonly logger = new Logger(${className}Controller.name);

    constructor(private readonly ${name.toLowerCase()}Service: ${className}Service) {}

    @Post()
    async create(@Body() createDto: Partial<${className}>): Promise<${className}> {
        this.logger.log(\`Creating ${name}\`);
        return this.${name.toLowerCase()}Service.create(createDto);
    }

    @Get()
    async findAll(): Promise<${className}[]> {
        this.logger.log(\`Finding all ${name}s\`);
        return this.${name.toLowerCase()}Service.findAll();
    }

    @Get(':id')
    async findById(@Param('id', ParseObjectIdPipe) id: string): Promise<${className} | null> {
        return this.${name.toLowerCase()}Service.findById(id);
    }

    @Put(':id')
    async update(
        @Param('id', ParseObjectIdPipe) id: string,
        @Body() updateDto: Partial<${className}>,
    ): Promise<${className} | null> {
        this.logger.log(\`Updating ${name}: \${id}\`);
        return this.${name.toLowerCase()}Service.update(id, updateDto);
    }

    @Delete(':id')
    async delete(@Param('id', ParseObjectIdPipe) id: string): Promise<{ success: boolean }> {
        const success = await this.${name.toLowerCase()}Service.delete(id);
        return { success };
    }
}
`;
    }

    /**
     * NestJS module template
     */
    private getNestJSModuleTemplate(name: string): string {
        const className = this.toPascalCase(name);
        return `import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { ${className}Controller } from './${name.toLowerCase()}.controller';
import { ${className}Service } from './${name.toLowerCase()}.service';
import { ${className}, ${className}Schema } from './schemas/${name.toLowerCase()}.schema';

@Module({
    imports: [
        MongooseModule.forFeature([
            { name: ${className}.name, schema: ${className}Schema },
        ]),
    ],
    controllers: [${className}Controller],
    providers: [${className}Service],
    exports: [${className}Service],
})
export class ${className}Module {}
`;
    }

    /**
     * NestJS DTO template
     */
    private getNestJSDtoTemplate(name: string): string {
        const className = this.toPascalCase(name);
        return `import { IsString, IsOptional, IsBoolean, IsDateString } from 'class-validator';

export class Create${className}Dto {
    @IsString()
    name: string;

    @IsString()
    @IsOptional()
    description?: string;

    @IsBoolean()
    @IsOptional()
    isActive?: boolean;
}

export class Update${className}Dto {
    @IsString()
    @IsOptional()
    name?: string;

    @IsString()
    @IsOptional()
    description?: string;

    @IsBoolean()
    @IsOptional()
    isActive?: boolean;
}
`;
    }

    /**
     * NestJS config template
     */
    private getNestJSConfigTemplate(): string {
        return `import { registerAs } from '@nestjs/config';

export default registerAs('app', () => ({
    nodeEnv: process.env.NODE_ENV || 'development',
    port: parseInt(process.env.PORT || '3000', 10),
    mongodbUri: process.env.MONGODB_URI || 'mongodb://localhost:27017/app',
    jwtSecret: process.env.JWT_SECRET || 'your-secret-key-change-in-production',
    jwtExpiresIn: process.env.JWT_EXPIRES_IN || '7d',
}));
`;
    }

    /**
     * TypeScript middleware template
     */
    private getTypeScriptMiddlewareTemplate(fileName: string, framework: string): string {
        const name = fileName.replace('.ts', '').replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
        const className = name.replace(/ /g, '') + 'Middleware';

        if (framework === 'fastify') {
            return `/**
 * ${className}
 */

import { FastifyRequest, FastifyReply, HookHandlerDoneFunction } from 'fastify';

export async function ${className}(
  request: FastifyRequest,
  reply: FastifyReply,
  done: HookHandlerDoneFunction
): Promise<void> {
  // Pre-processing
  console.log(\`[${className}] Processing: \${request.url}\`);
  
  // Continue to next handler
  done();
}

export default ${className};
`;
        }

        return `/**
 * ${className}
 */

import { Request, Response, NextFunction } from 'express';

export function ${className}(
  req: Request,
  res: Response,
  next: NextFunction
): void {
  console.log(\`[${className}] Processing: \${req.path}\`);
  next();
}

export default ${className};
`;
    }

    /**
     * TypeScript route template
     */
    private getTypeScriptRouteTemplate(fileName: string, framework: string, _blueprint: ArchitectureBlueprint): string {
        const routeName = fileName.replace('.ts', '').replace('-routes', '').replace('.routes', '');
        const className = this.toPascalCase(routeName);

        if (framework === 'fastify') {
            return `/**
 * ${className} Routes
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';

export async function ${routeName}Routes(app: FastifyInstance): Promise<void> {
  app.get('/', async (request: FastifyRequest, reply: FastifyReply) => {
    return { success: true, data: [] };
  });

  app.get('/:id', async (request: FastifyRequest, reply: FastifyReply) => {
    const { id } = request.params as { id: string };
    return { success: true, data: { id } };
  });

  app.post('/', async (request: FastifyRequest, reply: FastifyReply) => {
    return { success: true, data: request.body };
  });
}

export default ${routeName}Routes;
`;
        }

        return `/**
 * ${className} Routes
 */

import { Router, Request, Response } from 'express';

const router = Router();

router.get('/', async (req: Request, res: Response) => {
  res.json({ success: true, data: [] });
});

router.get('/:id', async (req: Request, res: Response) => {
  res.json({ success: true, data: { id: req.params.id } });
});

router.post('/', async (req: Request, res: Response) => {
  res.json({ success: true, data: req.body });
});

export default router;
`;
    }

    /**
     * TypeScript service template
     */
    private getTypeScriptServiceTemplate(fileName: string, _framework: string): string {
        const serviceName = fileName.replace('.service.ts', '').replace('.ts', '').replace('-service', '');
        const className = this.toPascalCase(serviceName) + 'Service';

        return `/**
 * ${className}
 */

export interface ${this.toPascalCase(serviceName)}Data {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  [key: string]: unknown;
}

export class ${className} {
  private initialized = false;

  constructor() {
    this.initialized = true;
    console.log(\`[${className}] Initialized\`);
  }

  async create(data: Partial<${this.toPascalCase(serviceName)}Data>): Promise<${this.toPascalCase(serviceName)}Data> {
    console.log(\`[${className}] Creating\`);
    return {
      id: 'generated-id',
      createdAt: new Date(),
      updatedAt: new Date(),
      ...data,
    } as ${this.toPascalCase(serviceName)}Data;
  }

  async findById(id: string): Promise<${this.toPascalCase(serviceName)}Data | null> {
    console.log(\`[${className}] Finding: \${id}\`);
    return null;
  }

  async findAll(): Promise<${this.toPascalCase(serviceName)}Data[]> {
    console.log(\`[${className}] Finding all\`);
    return [];
  }

  async update(id: string, data: Partial<${this.toPascalCase(serviceName)}Data>): Promise<${this.toPascalCase(serviceName)}Data | null> {
    console.log(\`[${className}] Updating: \${id}\`);
    return null;
  }

  async delete(id: string): Promise<boolean> {
    console.log(\`[${className}] Deleting: \${id}\`);
    return true;
  }
}

let instance: ${className} | null = null;

export function get${className}(): ${className} {
  if (!instance) {
    instance = new ${className}();
  }
  return instance;
}
`;
    }

    /**
     * TypeScript types template
     */
    private getTypeScriptTypesTemplate(_blueprint: ArchitectureBlueprint): string {
        return `/**
 * Shared Types
 */

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: {
    code: number;
    message: string;
  };
}

export interface PaginationParams {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

export interface User {
  id: string;
  email: string;
  name?: string;
  role: 'admin' | 'user' | 'guest';
  createdAt: Date;
  updatedAt: Date;
}
`;
    }

    /**
     * TypeScript config template
     */
    private getTypeScriptConfigTemplate(_framework: string): string {
        return `/**
 * Environment Configuration
 */

import { z } from 'zod';
import dotenv from 'dotenv';

dotenv.config();

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  PORT: z.string().transform(Number).default('3000'),
  HOST: z.string().default('0.0.0.0'),
  DATABASE_URL: z.string().optional(),
  REDIS_URL: z.string().optional(),
  JWT_SECRET: z.string().default('change-this-in-production'),
  CORS_ORIGINS: z.string().default('http://localhost:3000'),
});

const parsed = envSchema.safeParse(process.env);

if (!parsed.success) {
  console.error('Invalid environment variables');
  process.exit(1);
}

export const env = parsed.data;
export type Env = z.infer<typeof envSchema>;
`;
    }

    /**
     * Go file templates
     */
    private getGoTemplate(fileName: string, lowerPath: string, _blueprint: ArchitectureBlueprint): string | null {
        if (fileName === 'main.go') {
            return this.getGoMainTemplate();
        }
        if (lowerPath.includes('handler')) {
            return this.getGoHandlerTemplate(fileName);
        }
        if (lowerPath.includes('model')) {
            return this.getGoModelTemplate(fileName);
        }
        return null;
    }

    private getGoMainTemplate(): string {
        return `package main

import (
    "log"
    "net/http"
    "github.com/gorilla/mux"
)

func main() {
    r := mux.NewRouter()
    
    r.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
        w.WriteHeader(http.StatusOK)
        w.Write([]byte(\`{"status":"healthy"}\`))
    }).Methods("GET")
    
    log.Println("Server starting on :8080")
    log.Fatal(http.ListenAndServe(":8080", r))
}
`;
    }

    private getGoHandlerTemplate(fileName: string): string {
        const name = fileName.replace('.go', '');
        return `package handlers

import (
    "encoding/json"
    "net/http"
)

func ${this.toPascalCase(name)}Handler(w http.ResponseWriter, r *http.Request) {
    w.Header().Set("Content-Type", "application/json")
    json.NewEncoder(w).Encode(map[string]interface{}{
        "success": true,
        "data":    []interface{}{},
    })
}
`;
    }

    private getGoModelTemplate(fileName: string): string {
        const name = fileName.replace('.go', '');
        return `package models

import "time"

type ${this.toPascalCase(name)} struct {
    ID        uint      \`json:"id" gorm:"primaryKey"\`
    Name      string    \`json:"name"\`
    CreatedAt time.Time \`json:"created_at"\`
    UpdatedAt time.Time \`json:"updated_at"\`
}
`;
    }

    /**
     * Rust file templates
     */
    private getRustTemplate(fileName: string, lowerPath: string, _blueprint: ArchitectureBlueprint): string | null {
        if (fileName === 'main.rs') {
            return this.getRustMainTemplate();
        }
        if (lowerPath.includes('handler') || lowerPath.includes('route')) {
            return this.getRustHandlerTemplate(fileName);
        }
        return null;
    }

    private getRustMainTemplate(): string {
        return `use actix_web::{App, HttpServer, HttpResponse, Responder};

async fn health() -> impl Responder {
    HttpResponse::Ok().json(serde_json::json!({"status": "healthy"}))
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    println!("Server starting on :8080");
    HttpServer::new(|| {
        App::new()
            .route("/health", actix_web::web::get().to(health))
    })
    .bind("0.0.0.0:8080")?
    .run()
    .await
}
`;
    }

    private getRustHandlerTemplate(fileName: string): string {
        const name = fileName.replace('.rs', '');
        return `use actix_web::{HttpResponse, Responder};
use serde_json::json;

pub async fn ${this.toSnakeCase(name)}_handler() -> impl Responder {
    HttpResponse::Ok().json(json!({
        "success": true,
        "data": []
    }))
}
`;
    }

    /**
     * .env.example template
     */
    private getEnvExample(): string {
        return `# Application
NODE_ENV=development
PORT=3000
HOST=0.0.0.0

# Database
DATABASE_URL=

# Redis
REDIS_URL=redis://localhost:6379

# Security
JWT_SECRET=your-secret-key-change-in-production

# CORS
CORS_ORIGINS=http://localhost:3000
`;
    }

    /**
     * Convert string to PascalCase
     */
    private toPascalCase(str: string): string {
        return str
            .split(/[-_\s]+/)
            .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
            .join('');
    }

    /**
     * Convert string to snake_case
     */
    private toSnakeCase(str: string): string {
        return str
            .replace(/([A-Z])/g, '_$1')
            .toLowerCase()
            .replace(/^_/, '')
            .replace(/[-\s]+/g, '_');
    }
}

// Singleton
let instance: BlueprintEnforcer | null = null;

export function getBlueprintEnforcer(): BlueprintEnforcer {
    if (!instance) {
        instance = new BlueprintEnforcer();
    }
    return instance;
}

export function createBlueprintEnforcer(): BlueprintEnforcer {
    instance = new BlueprintEnforcer();
    return instance;
}
