/**
 * FileWriter Service
 * Writes generated code to actual files on disk
 *
 * Output structure:
 * output/
 * └── {projectId}/
 *     ├── src/
 *     │   └── {generated files}
 *     ├── package.json
 *     └── tsconfig.json
 */

import { injectable, unmanaged } from 'inversify';
import fs from 'fs/promises';
import path from 'path';

// ============================================
// TYPES
// ============================================

export interface GeneratedFile {
    path: string;          // Relative path like "src/auth/middleware.ts"
    content: string;       // File content
    type?: 'code' | 'config' | 'doc';
}

export interface WriteResult {
    success: boolean;
    projectPath: string;
    filesWritten: string[];
    errors: string[];
}

export interface FileWriterConfig {
    outputDir: string;     // Base output directory
    createPackageJson: boolean;
    createTsConfig: boolean;
}

// ============================================
// DEFAULT TEMPLATES
// ============================================

const DEFAULT_PACKAGE_JSON = (projectName: string) => JSON.stringify({
    name: projectName,
    version: "1.0.0",
    description: "Generated by Loveable Backend Orchestrator",
    main: "dist/index.js",
    scripts: {
        dev: "tsx watch src/index.ts",
        build: "tsc",
        start: "node dist/index.js",
        "type-check": "tsc --noEmit"
    },
    dependencies: {
        fastify: "^5.1.0",
        "@fastify/cors": "^10.0.1",
        "@fastify/jwt": "^9.0.1",
        zod: "^3.23.8",
        dotenv: "^16.4.5"
    },
    devDependencies: {
        "@types/node": "^22.10.1",
        typescript: "^5.7.2",
        tsx: "^4.19.2"
    }
}, null, 2);

const DEFAULT_TSCONFIG = JSON.stringify({
    compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        lib: ["ES2022"],
        outDir: "./dist",
        rootDir: "./src",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        declaration: true,
        declarationMap: true,
        sourceMap: true
    },
    include: ["src/**/*"],
    exclude: ["node_modules", "dist"]
}, null, 2);

const DEFAULT_INDEX = `/**
 * Generated Project Entry Point
 * Created by Loveable Backend Orchestrator
 */

import Fastify from 'fastify';

const app = Fastify({ logger: true });

app.get('/', async () => {
    return { message: 'Generated API is running!' };
});

const start = async () => {
    try {
        await app.listen({ port: 3001, host: '0.0.0.0' });
        console.log('Server running on http://localhost:3001');
    } catch (err) {
        app.log.error(err);
        process.exit(1);
    }
};

start();
`;

// ============================================
// FILEWRITER CLASS
// ============================================

@injectable()
export class FileWriterService {
    private config: FileWriterConfig;

    constructor(@unmanaged() config?: Partial<FileWriterConfig>) {
        // Default output to project root /output folder
        const defaultOutputDir = path.resolve(process.cwd(), '..', '..', 'output');

        this.config = {
            outputDir: config?.outputDir || defaultOutputDir,
            createPackageJson: config?.createPackageJson ?? true,
            createTsConfig: config?.createTsConfig ?? true,
        };
    }

    /**
     * Write generated files to a project folder
     */
    async writeProject(
        projectId: string,
        files: GeneratedFile[],
        options?: {
            projectName?: string;
            includeScaffold?: boolean;
            language?: string; // 'python' | 'typescript' | 'javascript' | 'go' | 'rust' | 'java' | etc.
        }
    ): Promise<WriteResult> {
        const projectPath = path.join(this.config.outputDir, projectId);
        const filesWritten: string[] = [];
        const errors: string[] = [];

        console.log(`[FILE-WRITER] Writing project to: ${projectPath}`);

        // Detect language from options or file extensions
        const langLower = options?.language?.toLowerCase() || '';

        // Languages that should NOT get TypeScript scaffold files
        const isNonTsProject =
            langLower === 'python' || files.some(f => f.path.endsWith('.py')) ||
            langLower === 'go' || langLower === 'golang' || files.some(f => f.path.endsWith('.go')) ||
            langLower === 'rust' || files.some(f => f.path.endsWith('.rs')) ||
            langLower === 'java' || files.some(f => f.path.endsWith('.java')) ||
            langLower === 'csharp' || langLower === 'c#' || files.some(f => f.path.endsWith('.cs')) ||
            langLower === 'cpp' || langLower === 'c++' || files.some(f => f.path.endsWith('.cpp')) ||
            langLower === 'ruby' || files.some(f => f.path.endsWith('.rb')) ||
            langLower === 'php' || files.some(f => f.path.endsWith('.php')) ||
            langLower === 'kotlin' || files.some(f => f.path.endsWith('.kt')) ||
            langLower === 'swift' || files.some(f => f.path.endsWith('.swift'));

        console.log(`[FILE-WRITER] Language: ${options?.language || 'unknown'}, isNonTsProject: ${isNonTsProject}`);

        try {
            // Create project directory
            await fs.mkdir(projectPath, { recursive: true });

            // Only create src/ folder for TypeScript/JavaScript projects
            if (!isNonTsProject) {
                await fs.mkdir(path.join(projectPath, 'src'), { recursive: true });
            }

            // Write scaffold files if requested (only for TypeScript/JavaScript)
            if (options?.includeScaffold !== false && !isNonTsProject) {
                // package.json
                if (this.config.createPackageJson) {
                    const packageJsonPath = path.join(projectPath, 'package.json');
                    await fs.writeFile(
                        packageJsonPath,
                        DEFAULT_PACKAGE_JSON(options?.projectName || projectId),
                        'utf-8'
                    );
                    filesWritten.push('package.json');
                    console.log(`[FILE-WRITER] ✅ Created package.json`);
                }

                // tsconfig.json
                if (this.config.createTsConfig) {
                    const tsconfigPath = path.join(projectPath, 'tsconfig.json');
                    await fs.writeFile(tsconfigPath, DEFAULT_TSCONFIG, 'utf-8');
                    filesWritten.push('tsconfig.json');
                    console.log(`[FILE-WRITER] ✅ Created tsconfig.json`);
                }

                // Default index.ts if not provided
                const hasIndex = files.some(f =>
                    f.path === 'src/index.ts' || f.path === 'index.ts'
                );
                if (!hasIndex) {
                    const indexPath = path.join(projectPath, 'src', 'index.ts');
                    await fs.writeFile(indexPath, DEFAULT_INDEX, 'utf-8');
                    filesWritten.push('src/index.ts');
                    console.log(`[FILE-WRITER] ✅ Created src/index.ts`);
                }
            }

            // Write generated files
            for (const file of files) {
                try {
                    // Normalize path (ensure it's under src/ if no src prefix)
                    let filePath = file.path;
                    if (!filePath.startsWith('src/') && !filePath.includes('/')) {
                        filePath = `src/${filePath}`;
                    }

                    const fullPath = path.join(projectPath, filePath);
                    const dir = path.dirname(fullPath);

                    // Create directory if needed
                    await fs.mkdir(dir, { recursive: true });

                    // Write file
                    await fs.writeFile(fullPath, file.content, 'utf-8');
                    filesWritten.push(filePath);
                    console.log(`[FILE-WRITER] ✅ Created ${filePath}`);

                } catch (error) {
                    const errorMsg = error instanceof Error ? error.message : 'Unknown error';
                    errors.push(`Failed to write ${file.path}: ${errorMsg}`);
                    console.error(`[FILE-WRITER] ❌ Failed to write ${file.path}: ${errorMsg}`);
                }
            }

            console.log(`[FILE-WRITER] Project written: ${filesWritten.length} files`);

            return {
                success: errors.length === 0,
                projectPath,
                filesWritten,
                errors,
            };

        } catch (error) {
            const errorMsg = error instanceof Error ? error.message : 'Unknown error';
            errors.push(`Failed to create project: ${errorMsg}`);
            console.error(`[FILE-WRITER] ❌ Project creation failed: ${errorMsg}`);

            return {
                success: false,
                projectPath,
                filesWritten,
                errors,
            };
        }
    }

    /**
     * Write a single file
     */
    async writeFile(projectId: string, file: GeneratedFile): Promise<boolean> {
        const result = await this.writeProject(projectId, [file], { includeScaffold: false });
        return result.success;
    }

    /**
     * Append content to an existing file
     */
    async appendToFile(projectId: string, filePath: string, content: string): Promise<boolean> {
        try {
            const fullPath = path.join(this.config.outputDir, projectId, filePath);
            await fs.appendFile(fullPath, content, 'utf-8');
            console.log(`[FILE-WRITER] ✅ Appended to ${filePath}`);
            return true;
        } catch (error) {
            console.error(`[FILE-WRITER] ❌ Failed to append to ${filePath}`);
            return false;
        }
    }

    /**
     * Check if a project exists
     */
    async projectExists(projectId: string): Promise<boolean> {
        try {
            const projectPath = path.join(this.config.outputDir, projectId);
            await fs.access(projectPath);
            return true;
        } catch {
            return false;
        }
    }

    /**
     * List files in a project
     */
    async listProjectFiles(projectId: string): Promise<string[]> {
        const projectPath = path.join(this.config.outputDir, projectId);
        const files: string[] = [];

        async function scanDir(dir: string, basePath: string) {
            const entries = await fs.readdir(dir, { withFileTypes: true });
            for (const entry of entries) {
                const relativePath = path.join(basePath, entry.name);
                if (entry.isDirectory()) {
                    if (entry.name !== 'node_modules') {
                        await scanDir(path.join(dir, entry.name), relativePath);
                    }
                } else {
                    files.push(relativePath);
                }
            }
        }

        try {
            await scanDir(projectPath, '');
            return files;
        } catch {
            return [];
        }
    }

    /**
     * Delete a project
     */
    async deleteProject(projectId: string): Promise<boolean> {
        try {
            const projectPath = path.join(this.config.outputDir, projectId);
            await fs.rm(projectPath, { recursive: true, force: true });
            console.log(`[FILE-WRITER] 🗑️ Deleted project: ${projectId}`);
            return true;
        } catch (error) {
            console.error(`[FILE-WRITER] ❌ Failed to delete project: ${projectId}`);
            return false;
        }
    }

    /**
     * Get output directory path
     */
    getOutputDir(): string {
        return this.config.outputDir;
    }

    /**
     * Get project path
     */
    getProjectPath(projectId: string): string {
        return path.join(this.config.outputDir, projectId);
    }
}

// ============================================
// SINGLETON
// ============================================

let fileWriterInstance: FileWriterService | null = null;

export function getFileWriter(): FileWriterService {
    if (!fileWriterInstance) {
        fileWriterInstance = new FileWriterService();
    }
    return fileWriterInstance;
}

export function createFileWriter(config?: Partial<FileWriterConfig>): FileWriterService {
    fileWriterInstance = new FileWriterService(config);
    return fileWriterInstance;
}
