/**
 * Project Scaffold Generator
 * 
 * Phase 17.3: Configuration Files & Project Structure
 * 
 * This service generates all the boilerplate files needed
 * for a complete, runnable project:
 * - package.json
 * - tsconfig.json
 * - .env.example
 * - .gitignore
 * - README.md
 * - docker-compose.yml (optional)
 */

export interface ScaffoldConfig {
    projectName: string;
    description?: string;
    techStack: {
        runtime: 'node' | 'bun' | 'deno';
        framework: 'fastify' | 'express' | 'hono';
        database: 'prisma' | 'drizzle' | 'supabase' | 'none';
        testing: 'vitest' | 'jest' | 'none';
        linting: 'eslint' | 'biome' | 'none';
    };
    features: {
        docker: boolean;
        cicd: boolean;
        authentication: boolean;
        rateLimit: boolean;
        swagger: boolean;
    };
    author?: string;
    license?: string;
}

export interface ScaffoldFile {
    path: string;
    content: string;
    type: 'config' | 'doc' | 'code';
}

export interface ScaffoldResult {
    files: ScaffoldFile[];
    dependencies: string[];
    devDependencies: string[];
    scripts: Record<string, string>;
}

// ============================================
// DEFAULT CONFIGURATIONS
// ============================================

const DEFAULT_CONFIG: ScaffoldConfig = {
    projectName: 'generated-api',
    description: 'Generated by Loveable Backend Orchestrator',
    techStack: {
        runtime: 'node',
        framework: 'fastify',
        database: 'prisma',
        testing: 'vitest',
        linting: 'eslint',
    },
    features: {
        docker: true,
        cicd: false,
        authentication: true,
        rateLimit: true,
        swagger: true,
    },
    author: 'Loveable Backend',
    license: 'MIT',
};

// ============================================
// PROJECT SCAFFOLD GENERATOR
// ============================================

export class ProjectScaffoldGenerator {
    private config: ScaffoldConfig;

    constructor(config?: Partial<ScaffoldConfig>) {
        this.config = { ...DEFAULT_CONFIG, ...config };
    }

    /**
     * Generate all scaffold files for a project
     */
    generate(): ScaffoldResult {
        const files: ScaffoldFile[] = [];
        const dependencies: string[] = [];
        const devDependencies: string[] = [];
        const scripts: Record<string, string> = {};

        console.log(`[SCAFFOLD] Generating project: ${this.config.projectName}`);

        // Core dependencies based on framework
        this.addFrameworkDependencies(dependencies, devDependencies, scripts);

        // Database dependencies
        this.addDatabaseDependencies(dependencies, devDependencies, scripts);

        // Testing dependencies
        this.addTestingDependencies(devDependencies, scripts);

        // Linting dependencies
        this.addLintingDependencies(devDependencies, scripts);

        // Feature-specific dependencies
        this.addFeatureDependencies(dependencies);

        // Generate files
        files.push(this.generatePackageJson(dependencies, devDependencies, scripts));
        files.push(this.generateTsConfig());
        files.push(this.generateEnvExample());
        files.push(this.generateGitIgnore());
        files.push(this.generateReadme());

        if (this.config.features.docker) {
            files.push(this.generateDockerfile());
            files.push(this.generateDockerCompose());
        }

        if (this.config.techStack.linting === 'eslint') {
            files.push(this.generateEslintConfig());
        }

        if (this.config.techStack.database === 'prisma') {
            files.push(this.generatePrismaSchema());
        }

        console.log(`[SCAFFOLD] Generated ${files.length} files`);

        return { files, dependencies, devDependencies, scripts };
    }

    /**
     * Add framework-specific dependencies
     */
    private addFrameworkDependencies(
        deps: string[],
        devDeps: string[],
        scripts: Record<string, string>
    ): void {
        // TypeScript & Node types
        devDeps.push('typescript', '@types/node', 'tsx');

        switch (this.config.techStack.framework) {
            case 'fastify':
                deps.push('fastify', '@fastify/cors', '@fastify/helmet');
                if (this.config.features.swagger) {
                    deps.push('@fastify/swagger', '@fastify/swagger-ui');
                }
                if (this.config.features.rateLimit) {
                    deps.push('@fastify/rate-limit');
                }
                break;
            case 'express':
                deps.push('express', 'cors', 'helmet');
                devDeps.push('@types/express', '@types/cors');
                break;
            case 'hono':
                deps.push('hono');
                break;
        }

        // Common dependencies
        deps.push('dotenv', 'zod', 'pino', 'pino-pretty');

        // Scripts
        scripts['dev'] = 'tsx watch src/index.ts';
        scripts['build'] = 'tsc';
        scripts['start'] = 'node dist/index.js';
    }

    /**
     * Add database dependencies
     */
    private addDatabaseDependencies(
        deps: string[],
        devDeps: string[],
        scripts: Record<string, string>
    ): void {
        switch (this.config.techStack.database) {
            case 'prisma':
                deps.push('@prisma/client');
                devDeps.push('prisma');
                scripts['db:generate'] = 'prisma generate';
                scripts['db:push'] = 'prisma db push';
                scripts['db:migrate'] = 'prisma migrate dev';
                scripts['db:studio'] = 'prisma studio';
                break;
            case 'drizzle':
                deps.push('drizzle-orm', 'postgres');
                devDeps.push('drizzle-kit');
                scripts['db:generate'] = 'drizzle-kit generate';
                scripts['db:push'] = 'drizzle-kit push';
                break;
            case 'supabase':
                deps.push('@supabase/supabase-js');
                break;
        }
    }

    /**
     * Add testing dependencies
     */
    private addTestingDependencies(
        devDeps: string[],
        scripts: Record<string, string>
    ): void {
        switch (this.config.techStack.testing) {
            case 'vitest':
                devDeps.push('vitest', '@vitest/coverage-v8');
                scripts['test'] = 'vitest run';
                scripts['test:watch'] = 'vitest';
                scripts['test:coverage'] = 'vitest run --coverage';
                break;
            case 'jest':
                devDeps.push('jest', '@types/jest', 'ts-jest');
                scripts['test'] = 'jest';
                scripts['test:watch'] = 'jest --watch';
                scripts['test:coverage'] = 'jest --coverage';
                break;
        }
    }

    /**
     * Add linting dependencies
     */
    private addLintingDependencies(
        devDeps: string[],
        scripts: Record<string, string>
    ): void {
        switch (this.config.techStack.linting) {
            case 'eslint':
                devDeps.push('eslint', '@typescript-eslint/eslint-plugin', '@typescript-eslint/parser');
                scripts['lint'] = 'eslint src --ext .ts';
                scripts['lint:fix'] = 'eslint src --ext .ts --fix';
                break;
            case 'biome':
                devDeps.push('@biomejs/biome');
                scripts['lint'] = 'biome check src';
                scripts['lint:fix'] = 'biome check src --write';
                break;
        }
    }

    /**
     * Add feature-specific dependencies
     */
    private addFeatureDependencies(deps: string[]): void {
        if (this.config.features.authentication) {
            deps.push('jsonwebtoken', 'bcryptjs');
        }
    }

    /**
     * Generate package.json
     */
    private generatePackageJson(
        deps: string[],
        devDeps: string[],
        scripts: Record<string, string>
    ): ScaffoldFile {
        const packageJson = {
            name: this.config.projectName.toLowerCase().replace(/\s+/g, '-'),
            version: '1.0.0',
            description: this.config.description,
            main: 'dist/index.js',
            type: 'module',
            scripts: {
                ...scripts,
                'typecheck': 'tsc --noEmit',
                'clean': 'rm -rf dist',
                'prepare': 'npm run build',
            },
            keywords: ['api', 'backend', 'typescript', this.config.techStack.framework],
            author: this.config.author,
            license: this.config.license,
            dependencies: Object.fromEntries(deps.sort().map(d => [d, 'latest'])),
            devDependencies: Object.fromEntries(devDeps.sort().map(d => [d, 'latest'])),
            engines: {
                node: '>=18.0.0',
            },
        };

        // Add prisma seed script if using Prisma
        if (this.config.techStack.database === 'prisma') {
            (packageJson as Record<string, unknown>)['prisma'] = {
                seed: 'tsx prisma/seed.ts',
            };
        }

        return {
            path: 'package.json',
            content: JSON.stringify(packageJson, null, 2),
            type: 'config',
        };
    }

    /**
     * Generate tsconfig.json
     */
    private generateTsConfig(): ScaffoldFile {
        const tsConfig = {
            compilerOptions: {
                target: 'ES2022',
                module: 'ESNext',
                moduleResolution: 'Node',
                lib: ['ES2022'],
                outDir: './dist',
                rootDir: './src',
                strict: true,
                esModuleInterop: true,
                skipLibCheck: true,
                forceConsistentCasingInFileNames: true,
                resolveJsonModule: true,
                declaration: true,
                declarationMap: true,
                sourceMap: true,
                noUnusedLocals: true,
                noUnusedParameters: true,
                noImplicitReturns: true,
                noFallthroughCasesInSwitch: true,
            },
            include: ['src/**/*'],
            exclude: ['node_modules', 'dist'],
        };

        return {
            path: 'tsconfig.json',
            content: JSON.stringify(tsConfig, null, 2),
            type: 'config',
        };
    }

    /**
     * Generate .env.example
     */
    private generateEnvExample(): ScaffoldFile {
        const lines: string[] = [
            '# ===========================================',
            `# ${this.config.projectName} - Environment Variables`,
            '# ===========================================',
            '',
            '# Server',
            'PORT=3000',
            'HOST=0.0.0.0',
            'NODE_ENV=development',
            'LOG_LEVEL=info',
            '',
        ];

        // Database
        if (this.config.techStack.database !== 'none') {
            lines.push('# Database');
            switch (this.config.techStack.database) {
                case 'prisma':
                case 'drizzle':
                    lines.push('DATABASE_URL=postgresql://user:password@localhost:5432/mydb');
                    break;
                case 'supabase':
                    lines.push('SUPABASE_URL=https://your-project.supabase.co');
                    lines.push('SUPABASE_ANON_KEY=your-anon-key');
                    lines.push('SUPABASE_SERVICE_KEY=your-service-key');
                    break;
            }
            lines.push('');
        }

        // Authentication
        if (this.config.features.authentication) {
            lines.push('# Authentication');
            lines.push('JWT_SECRET=your-super-secret-jwt-key-min-32-chars');
            lines.push('JWT_EXPIRES_IN=7d');
            lines.push('BCRYPT_ROUNDS=12');
            lines.push('');
        }

        // Rate Limiting
        if (this.config.features.rateLimit) {
            lines.push('# Rate Limiting');
            lines.push('RATE_LIMIT_MAX=100');
            lines.push('RATE_LIMIT_WINDOW_MS=60000');
            lines.push('');
        }

        return {
            path: '.env.example',
            content: lines.join('\n'),
            type: 'config',
        };
    }

    /**
     * Generate .gitignore
     */
    private generateGitIgnore(): ScaffoldFile {
        const content = `# Dependencies
node_modules/
.pnpm-store/

# Build output
dist/
build/
*.tsbuildinfo

# Environment
.env
.env.local
.env.*.local

# IDE
.vscode/
.idea/
*.swp
*.swo
.DS_Store

# Logs
logs/
*.log
npm-debug.log*
pnpm-debug.log*

# Testing
coverage/
.nyc_output/

# Database
*.db
*.sqlite

# Misc
.cache/
tmp/
temp/
`;

        return {
            path: '.gitignore',
            content,
            type: 'config',
        };
    }

    /**
     * Generate README.md
     */
    private generateReadme(): ScaffoldFile {
        const { projectName, description, techStack, features } = this.config;

        const content = `# ${projectName}

${description}

## 🚀 Quick Start

### Prerequisites
- Node.js >= 18.0.0
- ${techStack.database !== 'none' ? 'PostgreSQL (or your database of choice)' : ''}

### Installation

\`\`\`bash
# Install dependencies
npm install

# Copy environment variables
cp .env.example .env

# Edit .env with your values
nano .env
${techStack.database === 'prisma' ? `
# Generate Prisma client
npm run db:generate

# Push database schema
npm run db:push
` : ''}
# Start development server
npm run dev
\`\`\`

## 📁 Project Structure

\`\`\`
src/
├── index.ts          # Application entry point
├── routes/           # API route handlers
├── services/         # Business logic
├── schemas/          # Validation schemas (Zod)
├── lib/              # Shared utilities
│   ├── prisma.ts     # Database client
│   └── logger.ts     # Logging setup
└── types/            # TypeScript type definitions
\`\`\`

## 🔧 Available Scripts

| Script | Description |
|--------|-------------|
| \`npm run dev\` | Start development server with hot reload |
| \`npm run build\` | Build for production |
| \`npm start\` | Run production server |
| \`npm test\` | Run tests |
| \`npm run lint\` | Lint code |
${techStack.database === 'prisma' ? `| \`npm run db:generate\` | Generate Prisma client |
| \`npm run db:push\` | Push schema to database |
| \`npm run db:migrate\` | Run migrations |
| \`npm run db:studio\` | Open Prisma Studio |` : ''}

## 🔒 Features

${features.authentication ? '- ✅ JWT Authentication' : ''}
${features.rateLimit ? '- ✅ Rate Limiting' : ''}
${features.swagger ? '- ✅ Swagger/OpenAPI Documentation' : ''}
${features.docker ? '- ✅ Docker Support' : ''}

## 📚 API Documentation

${features.swagger ? 'API documentation is available at `/documentation` when the server is running.' : 'See the routes folder for available endpoints.'}

## 🐳 Docker

${features.docker ? `\`\`\`bash
# Build and run with Docker Compose
docker-compose up -d

# View logs
docker-compose logs -f
\`\`\`` : 'Docker support not enabled.'}

## 📝 License

${this.config.license}

---

Generated by **Loveable Backend Orchestrator**
`;

        return {
            path: 'README.md',
            content,
            type: 'doc',
        };
    }

    /**
     * Generate Dockerfile
     */
    private generateDockerfile(): ScaffoldFile {
        const content = `# Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./
${this.config.techStack.database === 'prisma' ? 'COPY prisma ./prisma/' : ''}

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

${this.config.techStack.database === 'prisma' ? '# Generate Prisma client\nRUN npm run db:generate\n' : ''}
# Build TypeScript
RUN npm run build

# Stage 2: Production
FROM node:20-alpine AS production

WORKDIR /app

# Copy package files
COPY package*.json ./
${this.config.techStack.database === 'prisma' ? 'COPY prisma ./prisma/' : ''}

# Install production dependencies only
RUN npm ci --only=production

${this.config.techStack.database === 'prisma' ? '# Generate Prisma client\nRUN npx prisma generate\n' : ''}
# Copy built files
COPY --from=builder /app/dist ./dist

# Set environment
ENV NODE_ENV=production

# Expose port
EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1

# Start server
CMD ["node", "dist/index.js"]
`;

        return {
            path: 'Dockerfile',
            content,
            type: 'config',
        };
    }

    /**
     * Generate docker-compose.yml
     */
    private generateDockerCompose(): ScaffoldFile {
        const projectSlug = this.config.projectName.toLowerCase().replace(/\s+/g, '-');

        const content = `version: '3.8'

services:
  api:
    build: .
    container_name: ${projectSlug}-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
${this.config.techStack.database !== 'none' ? `      - DATABASE_URL=postgresql://postgres:postgres@db:5432/${projectSlug}` : ''}
    depends_on:
${this.config.techStack.database !== 'none' ? '      db:\n        condition: service_healthy' : '      - redis'}
    networks:
      - ${projectSlug}-network
    restart: unless-stopped

${this.config.techStack.database !== 'none' ? `  db:
    image: postgres:15-alpine
    container_name: ${projectSlug}-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${projectSlug}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ${projectSlug}-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
` : ''}
  redis:
    image: redis:7-alpine
    container_name: ${projectSlug}-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ${projectSlug}-network
    restart: unless-stopped

networks:
  ${projectSlug}-network:
    driver: bridge

volumes:
${this.config.techStack.database !== 'none' ? '  postgres-data:' : ''}
  redis-data:
`;

        return {
            path: 'docker-compose.yml',
            content,
            type: 'config',
        };
    }

    /**
     * Generate ESLint config
     */
    private generateEslintConfig(): ScaffoldFile {
        const config = {
            root: true,
            parser: '@typescript-eslint/parser',
            parserOptions: {
                ecmaVersion: 2022,
                sourceType: 'module',
                project: './tsconfig.json',
            },
            plugins: ['@typescript-eslint'],
            extends: [
                'eslint:recommended',
                'plugin:@typescript-eslint/recommended',
            ],
            env: {
                node: true,
                es2022: true,
            },
            rules: {
                '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
                '@typescript-eslint/explicit-function-return-type': 'off',
                '@typescript-eslint/no-explicit-any': 'warn',
                'no-console': 'off',
            },
            ignorePatterns: ['dist', 'node_modules'],
        };

        return {
            path: '.eslintrc.json',
            content: JSON.stringify(config, null, 2),
            type: 'config',
        };
    }

    /**
     * Generate basic Prisma schema
     */
    private generatePrismaSchema(): ScaffoldFile {
        const content = `// Prisma Schema for ${this.config.projectName}
// Learn more: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// Add your models here
// Example:
// model User {
//   id        String   @id @default(cuid())
//   email     String   @unique
//   name      String?
//   createdAt DateTime @default(now())
//   updatedAt DateTime @updatedAt
// }
`;

        return {
            path: 'prisma/schema.prisma',
            content,
            type: 'config',
        };
    }
}

// ============================================
// FACTORY FUNCTIONS
// ============================================

export function createProjectScaffold(config?: Partial<ScaffoldConfig>): ScaffoldResult {
    const generator = new ProjectScaffoldGenerator(config);
    return generator.generate();
}

export function getDefaultScaffoldConfig(): ScaffoldConfig {
    return { ...DEFAULT_CONFIG };
}
