/**
 * Test Generator Service
 * 
 * Phase 17.4: Test File Generation
 * 
 * Generates unit tests and integration tests for:
 * - Services
 * - Routes/Endpoints
 * - Utilities
 */

export interface TestFile {
    path: string;
    content: string;
    type: 'unit' | 'integration' | 'e2e';
}

export interface TestGeneratorConfig {
    framework: 'vitest' | 'jest';
    coverage: boolean;
    mockDatabase: boolean;
}

export interface GeneratedTestResult {
    tests: TestFile[];
    testSetupFile: TestFile;
    mockFiles: TestFile[];
}

// ============================================
// TEST GENERATOR
// ============================================

export class TestGenerator {
    private config: TestGeneratorConfig;

    constructor(config?: Partial<TestGeneratorConfig>) {
        this.config = {
            framework: config?.framework || 'vitest',
            coverage: config?.coverage ?? true,
            mockDatabase: config?.mockDatabase ?? true,
        };
    }

    /**
     * Generate tests for a service file
     */
    generateServiceTest(
        servicePath: string,
        serviceContent: string,
        serviceName: string
    ): TestFile {
        const testPath = servicePath.replace('.ts', '.test.ts');

        // Extract exported functions/classes
        const exports = this.extractExports(serviceContent);
        const isClass = serviceContent.includes('export class');

        let testContent: string;

        if (isClass) {
            testContent = this.generateClassTest(serviceName, exports, servicePath);
        } else {
            testContent = this.generateFunctionTest(serviceName, exports, servicePath);
        }

        return {
            path: testPath,
            content: testContent,
            type: 'unit',
        };
    }

    /**
     * Generate integration tests for routes
     */
    generateRouteTest(
        routePath: string,
        routeContent: string,
        _routeName: string
    ): TestFile {
        const testPath = routePath.replace('.ts', '.test.ts');

        // Extract endpoints
        const endpoints = this.extractEndpoints(routeContent);

        const testContent = this.generateEndpointTests(endpoints, routePath);

        return {
            path: testPath,
            content: testContent,
            type: 'integration',
        };
    }

    /**
     * Generate test setup file
     */
    generateSetupFile(): TestFile {
        const content = this.config.framework === 'vitest'
            ? this.generateVitestSetup()
            : this.generateJestSetup();

        return {
            path: `src/tests/setup.${this.config.framework === 'vitest' ? 'ts' : 'ts'}`,
            content,
            type: 'unit',
        };
    }

    /**
     * Generate database mock file
     */
    generateDatabaseMock(): TestFile {
        const content = `/**
 * Database Mock for Testing
 * Auto-generated by Loveable Backend
 */

import { vi } from 'vitest';

// Mock Prisma Client
export const mockPrisma = {
    user: {
        findMany: vi.fn(),
        findUnique: vi.fn(),
        findFirst: vi.fn(),
        create: vi.fn(),
        update: vi.fn(),
        delete: vi.fn(),
        count: vi.fn(),
    },
    // Add more models as needed
    $connect: vi.fn(),
    $disconnect: vi.fn(),
    $transaction: vi.fn((callback) => callback(mockPrisma)),
};

// Mock the Prisma module
vi.mock('@prisma/client', () => ({
    PrismaClient: vi.fn(() => mockPrisma),
}));

// Reset all mocks before each test
export function resetMocks() {
    Object.values(mockPrisma).forEach((model) => {
        if (typeof model === 'object' && model !== null) {
            Object.values(model).forEach((method) => {
                if (typeof method === 'function' && 'mockReset' in method) {
                    (method as { mockReset: () => void }).mockReset();
                }
            });
        }
    });
}

// Helper to mock successful responses
export function mockSuccess<T>(model: string, method: string, data: T) {
    const modelObj = mockPrisma[model as keyof typeof mockPrisma];
    if (modelObj && typeof modelObj === 'object' && method in modelObj) {
        (modelObj as Record<string, ReturnType<typeof vi.fn>>)[method].mockResolvedValue(data);
    }
}

// Helper to mock errors
export function mockError(model: string, method: string, error: Error) {
    const modelObj = mockPrisma[model as keyof typeof mockPrisma];
    if (modelObj && typeof modelObj === 'object' && method in modelObj) {
        (modelObj as Record<string, ReturnType<typeof vi.fn>>)[method].mockRejectedValue(error);
    }
}

export { mockPrisma as prisma };
`;

        return {
            path: 'src/tests/mocks/prisma.ts',
            content,
            type: 'unit',
        };
    }

    /**
     * Generate vitest config
     */
    generateVitestConfig(): TestFile {
        const content = `import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        globals: true,
        environment: 'node',
        setupFiles: ['./src/tests/setup.ts'],
        include: ['src/**/*.{test,spec}.ts'],
        exclude: ['node_modules', 'dist'],
        coverage: {
            provider: 'v8',
            reporter: ['text', 'json', 'html'],
            exclude: [
                'node_modules',
                'dist',
                '**/*.d.ts',
                '**/*.test.ts',
                '**/tests/**',
            ],
        },
        testTimeout: 10000,
        hookTimeout: 10000,
    },
});
`;

        return {
            path: 'vitest.config.ts',
            content,
            type: 'unit',
        };
    }

    // ============================================
    // PRIVATE HELPERS
    // ============================================

    private extractExports(content: string): string[] {
        const exports: string[] = [];

        // Match exported functions and classes
        const pattern = /export\s+(?:async\s+)?(?:function|class|const|let)\s+(\w+)/g;
        let match;
        while ((match = pattern.exec(content)) !== null) {
            exports.push(match[1]);
        }

        return exports;
    }

    private extractEndpoints(content: string): Array<{ method: string; path: string }> {
        const endpoints: Array<{ method: string; path: string }> = [];

        // Match Fastify route definitions
        const pattern = /app\.(get|post|put|patch|delete)\s*\(\s*['"`]([^'"`]+)['"`]/gi;
        let match;
        while ((match = pattern.exec(content)) !== null) {
            endpoints.push({
                method: match[1].toUpperCase(),
                path: match[2],
            });
        }

        return endpoints;
    }

    private generateClassTest(
        className: string,
        _exports: string[],
        sourcePath: string
    ): string {
        const importPath = sourcePath.replace(/\.ts$/, '').replace(/^src\//, '../');

        return `/**
 * Unit Tests for ${className}
 * Auto-generated by Loveable Backend
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';
import { ${className} } from '${importPath}';

describe('${className}', () => {
    let instance: ${className};

    beforeEach(() => {
        vi.clearAllMocks();
        instance = new ${className}();
    });

    describe('initialization', () => {
        it('should create an instance', () => {
            expect(instance).toBeDefined();
            expect(instance).toBeInstanceOf(${className});
        });
    });

    // TODO: Add more specific tests for each method
    // Example:
    // describe('methodName', () => {
    //     it('should do something', async () => {
    //         const result = await instance.methodName(input);
    //         expect(result).toBeDefined();
    //     });
    // });
});
`;
    }

    private generateFunctionTest(
        moduleName: string,
        exports: string[],
        sourcePath: string
    ): string {
        const importPath = sourcePath.replace(/\.ts$/, '').replace(/^src\//, '../');
        const importList = exports.join(', ');

        const testCases = exports.map(exp => `
    describe('${exp}', () => {
        it('should be defined', () => {
            expect(${exp}).toBeDefined();
        });

        // TODO: Add specific test cases
    });`).join('\n');

        return `/**
 * Unit Tests for ${moduleName}
 * Auto-generated by Loveable Backend
 */

import { describe, it, expect, vi } from 'vitest';
import { ${importList} } from '${importPath}';

describe('${moduleName}', () => {
    beforeEach(() => {
        vi.clearAllMocks();
    });
${testCases}
});
`;
    }

    private generateEndpointTests(
        endpoints: Array<{ method: string; path: string }>,
        _sourcePath: string
    ): string {
        const testCases = endpoints.map(ep => `
    describe('${ep.method} ${ep.path}', () => {
        it('should return 200 on success', async () => {
            const response = await app.inject({
                method: '${ep.method}',
                url: '${ep.path}',
            });

            expect(response.statusCode).toBe(200);
        });

        it('should handle errors gracefully', async () => {
            // TODO: Add error handling tests
        });
    });`).join('\n');

        return `/**
 * Integration Tests for Routes
 * Auto-generated by Loveable Backend
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import Fastify, { FastifyInstance } from 'fastify';

describe('Route Integration Tests', () => {
    let app: FastifyInstance;

    beforeAll(async () => {
        app = Fastify({ logger: false });
        // TODO: Register routes
        await app.ready();
    });

    afterAll(async () => {
        await app.close();
    });
${testCases}
});
`;
    }

    private generateVitestSetup(): string {
        return `/**
 * Vitest Test Setup
 * Auto-generated by Loveable Backend
 */

import { beforeAll, afterAll, beforeEach } from 'vitest';
${this.config.mockDatabase ? "import { resetMocks } from './mocks/prisma';" : ''}

// Global test setup
beforeAll(async () => {
    // Set test environment variables
    process.env.NODE_ENV = 'test';
    process.env.LOG_LEVEL = 'silent';
    
    console.log('🧪 Test suite starting...');
});

// Reset mocks before each test
beforeEach(() => {
${this.config.mockDatabase ? '    resetMocks();' : '    // No mock reset needed'}
});

// Global test teardown
afterAll(async () => {
    console.log('✅ Test suite complete');
});

// Extend expect with custom matchers if needed
// expect.extend({});
`;
    }

    private generateJestSetup(): string {
        return `/**
 * Jest Test Setup
 * Auto-generated by Loveable Backend
 */

${this.config.mockDatabase ? "import { resetMocks } from './mocks/prisma';" : ''}

// Global test setup
beforeAll(async () => {
    process.env.NODE_ENV = 'test';
    process.env.LOG_LEVEL = 'silent';
    
    console.log('🧪 Test suite starting...');
});

// Reset mocks before each test
beforeEach(() => {
${this.config.mockDatabase ? '    resetMocks();' : '    // No mock reset needed'}
});

// Global test teardown
afterAll(async () => {
    console.log('✅ Test suite complete');
});
`;
    }
}

// ============================================
// SINGLETON & FACTORY
// ============================================

let testGeneratorInstance: TestGenerator | null = null;

export function getTestGenerator(): TestGenerator {
    if (!testGeneratorInstance) {
        testGeneratorInstance = new TestGenerator();
    }
    return testGeneratorInstance;
}

export function createTestGenerator(config?: Partial<TestGeneratorConfig>): TestGenerator {
    testGeneratorInstance = new TestGenerator(config);
    return testGeneratorInstance;
}
