/**
 * Test Agent Templates
 * Code generation templates for various test types
 */

// ============================================
// VITEST CONFIGURATION TEMPLATE
// ============================================

export const VITEST_CONFIG_TEMPLATE = `/// <reference types="vitest" />
import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        globals: true,
        environment: '{{ENVIRONMENT}}',
        include: ['**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts}'],
        exclude: ['node_modules', 'dist', '.idea', '.git', '.cache'],
        coverage: {
            provider: 'v8',
            reporter: ['text', 'json', 'html', 'lcov'],
            reportsDirectory: './coverage',
            exclude: [
                'node_modules/',
                'dist/',
                '**/*.d.ts',
                'test/**',
                '**/*.test.{js,ts}',
            ],
            thresholds: {
                statements: {{COVERAGE_STATEMENTS}},
                branches: {{COVERAGE_BRANCHES}},
                functions: {{COVERAGE_FUNCTIONS}},
                lines: {{COVERAGE_LINES}},
            },
        },
        setupFiles: [{{SETUP_FILES}}],
        testTimeout: {{TEST_TIMEOUT}},
        hookTimeout: {{HOOK_TIMEOUT}},
        teardownTimeout: 10000,
        pool: 'threads',
        poolOptions: {
            threads: {
                maxThreads: {{MAX_CONCURRENCY}},
            },
        },
    },
});
`;

// ============================================
// JEST CONFIGURATION TEMPLATE
// ============================================

export const JEST_CONFIG_TEMPLATE = `/** @type {import('jest').Config} */
module.exports = {
    preset: 'ts-jest',
    testEnvironment: '{{ENVIRONMENT}}',
    rootDir: '.',
    testMatch: ['**/*.test.ts', '**/*.spec.ts'],
    collectCoverageFrom: [
        'src/**/*.ts',
        '!src/**/*.d.ts',
        '!src/**/*.test.ts',
    ],
    coverageThreshold: {
        global: {
            statements: {{COVERAGE_STATEMENTS}},
            branches: {{COVERAGE_BRANCHES}},
            functions: {{COVERAGE_FUNCTIONS}},
            lines: {{COVERAGE_LINES}},
        },
    },
    coverageReporters: ['text', 'lcov', 'html'],
    moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/src/$1',
    },
    setupFilesAfterEnv: [{{SETUP_FILES}}],
    testTimeout: {{TEST_TIMEOUT}},
    maxWorkers: {{MAX_CONCURRENCY}},
    verbose: true,
    clearMocks: true,
    restoreMocks: true,
};
`;

// ============================================
// UNIT TEST TEMPLATE
// ============================================

export const UNIT_TEST_TEMPLATE = `/**
 * Unit Tests for {{MODULE_NAME}}
 * Generated by Test Agent
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
{{IMPORTS}}

describe('{{MODULE_NAME}}', () => {
    {{BEFORE_EACH}}
    
    {{AFTER_EACH}}
    
{{TEST_CASES}}
});
`;

export const TEST_CASE_TEMPLATE = `    describe('{{FUNCTION_NAME}}', () => {
        it('should {{TEST_DESCRIPTION}}', {{ASYNC}}() => {
            // Arrange
            {{ARRANGE}}
            
            // Act
            {{ACT}}
            
            // Assert
            {{ASSERT}}
        });
{{EDGE_CASES}}
    });
`;

export const EDGE_CASE_TEMPLATE = `
        it('should handle {{EDGE_CASE_NAME}}', {{ASYNC}}() => {
            // Arrange
            {{ARRANGE}}
            
            // Act & Assert
            {{ACT_ASSERT}}
        });
`;

// ============================================
// MOCK GENERATION TEMPLATE
// ============================================

export const MOCK_FILE_TEMPLATE = `/**
 * Mocks for {{MODULE_NAME}}
 * Generated by Test Agent
 */

import { vi } from 'vitest';

{{MOCK_IMPLEMENTATIONS}}

export const create{{MODULE_NAME}}Mock = () => ({
{{MOCK_EXPORTS}}
});

export const reset{{MODULE_NAME}}Mocks = () => {
{{MOCK_RESETS}}
};
`;

export const MOCK_FUNCTION_TEMPLATE = `export const mock{{FUNCTION_NAME}} = vi.fn({{MOCK_IMPLEMENTATION}});
`;

export const MOCK_ASYNC_FUNCTION_TEMPLATE = `export const mock{{FUNCTION_NAME}} = vi.fn().mockResolvedValue({{RETURN_VALUE}});
`;

// ============================================
// FIXTURE TEMPLATE
// ============================================

export const FIXTURE_FILE_TEMPLATE = `/**
 * Test Fixtures for {{MODULE_NAME}}
 * Generated by Test Agent
 */

{{FIXTURE_IMPORTS}}

// ============================================
// SAMPLE DATA
// ============================================

{{SAMPLE_DATA}}

// ============================================
// FACTORY FUNCTIONS
// ============================================

{{FACTORY_FUNCTIONS}}

// ============================================
// FIXTURE BUILDER
// ============================================

export const createFixture = <T extends Record<string, unknown>>(
    base: T,
    overrides: Partial<T> = {}
): T => ({
    ...base,
    ...overrides,
});
`;

export const FACTORY_FUNCTION_TEMPLATE = `export const create{{ENTITY_NAME}} = (overrides: Partial<{{ENTITY_TYPE}}> = {}): {{ENTITY_TYPE}} => ({
{{DEFAULT_VALUES}}
    ...overrides,
});
`;

// ============================================
// INTEGRATION TEST TEMPLATE
// ============================================

export const INTEGRATION_TEST_TEMPLATE = `/**
 * Integration Tests for {{SERVICE_NAME}}
 * Generated by Test Agent
 */

import { describe, it, expect, beforeAll, afterAll, beforeEach, afterEach } from 'vitest';
{{IMPORTS}}

describe('{{SERVICE_NAME}} Integration', () => {
    {{SETUP_VARS}}
    
    beforeAll(async () => {
        // Setup test environment
        {{BEFORE_ALL}}
    });
    
    afterAll(async () => {
        // Teardown test environment
        {{AFTER_ALL}}
    });
    
    beforeEach(async () => {
        {{BEFORE_EACH}}
    });
    
    afterEach(async () => {
        {{AFTER_EACH}}
    });
    
{{TEST_CASES}}
});
`;

export const INTEGRATION_TEST_CASE_TEMPLATE = `    describe('{{ENDPOINT_OR_METHOD}}', () => {
        it('should {{TEST_DESCRIPTION}}', async () => {
            // Arrange
            {{ARRANGE}}
            
            // Act
            {{ACT}}
            
            // Assert
            {{ASSERT}}
        });
        
        it('should handle errors gracefully', async () => {
            // Arrange
            {{ERROR_ARRANGE}}
            
            // Act & Assert
            {{ERROR_ACT_ASSERT}}
        });
    });
`;

// ============================================
// API TEST TEMPLATE
// ============================================

export const API_TEST_TEMPLATE = `/**
 * API Tests for {{ENDPOINT_NAME}}
 * Generated by Test Agent
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import supertest from 'supertest';
{{IMPORTS}}

describe('API: {{ENDPOINT_NAME}}', () => {
    let request: supertest.SuperTest<supertest.Test>;
    {{AUTH_VARS}}
    
    beforeAll(async () => {
        // Setup API test client
        {{BEFORE_ALL}}
        request = supertest(app);
    });
    
    afterAll(async () => {
        {{AFTER_ALL}}
    });
    
{{TEST_CASES}}
});
`;

export const API_TEST_CASE_TEMPLATE = `    describe('{{METHOD}} {{PATH}}', () => {
        it('should return {{EXPECTED_STATUS}} on success', async () => {
            const response = await request
                .{{METHOD_LOWER}}('{{PATH}}')
                {{HEADERS}}
                {{BODY}}
                .expect({{EXPECTED_STATUS}});
            
            {{ASSERTIONS}}
        });
        
        it('should return 400 on invalid input', async () => {
            const response = await request
                .{{METHOD_LOWER}}('{{PATH}}')
                {{HEADERS}}
                .send({{INVALID_BODY}})
                .expect(400);
            
            expect(response.body).toHaveProperty('error');
        });
        
        {{AUTH_TEST}}
    });
`;

// ============================================
// E2E TEST TEMPLATE (PLAYWRIGHT)
// ============================================

export const PLAYWRIGHT_CONFIG_TEMPLATE = `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
    testDir: './tests/e2e',
    fullyParallel: true,
    forbidOnly: !!process.env.CI,
    retries: process.env.CI ? 2 : 0,
    workers: process.env.CI ? 1 : undefined,
    reporter: [
        ['html', { outputFolder: 'playwright-report' }],
        ['json', { outputFile: 'test-results.json' }],
    ],
    use: {
        baseURL: '{{BASE_URL}}',
        trace: 'on-first-retry',
        screenshot: '{{SCREENSHOT_MODE}}',
        video: '{{VIDEO_MODE}}',
    },
    projects: [
{{BROWSER_PROJECTS}}
    ],
    webServer: {
        command: 'npm run dev',
        url: '{{BASE_URL}}',
        reuseExistingServer: !process.env.CI,
        timeout: 120 * 1000,
    },
});
`;

export const BROWSER_PROJECT_TEMPLATE = `        {
            name: '{{BROWSER}}',
            use: { ...devices['{{DEVICE}}'] },
        },
`;

export const E2E_TEST_TEMPLATE = `/**
 * E2E Tests: {{PAGE_NAME}}
 * Generated by Test Agent
 */

import { test, expect } from '@playwright/test';
{{IMPORTS}}

test.describe('{{PAGE_NAME}}', () => {
    test.beforeEach(async ({ page }) => {
        await page.goto('{{PAGE_URL}}');
    });
    
{{TEST_CASES}}
});
`;

export const E2E_TEST_CASE_TEMPLATE = `    test('{{TEST_NAME}}', async ({ page }) => {
{{STEPS}}
    });
`;

export const E2E_STEP_TEMPLATES: Record<string, string> = {
    navigate: `        await page.goto('{{VALUE}}');`,
    click: `        await page.locator('{{SELECTOR}}').click();`,
    fill: `        await page.locator('{{SELECTOR}}').fill('{{VALUE}}');`,
    select: `        await page.locator('{{SELECTOR}}').selectOption('{{VALUE}}');`,
    wait: `        await page.waitForSelector('{{SELECTOR}}', { timeout: {{TIMEOUT}} });`,
    assert: `        await expect(page.locator('{{SELECTOR}}')).{{ASSERTION}}('{{EXPECTED}}');`,
    screenshot: `        await page.screenshot({ path: 'screenshots/{{VALUE}}.png', fullPage: true });`,
};

// ============================================
// PAGE OBJECT MODEL TEMPLATE
// ============================================

export const PAGE_OBJECT_TEMPLATE = `/**
 * Page Object: {{PAGE_NAME}}
 * Generated by Test Agent
 */

import { Page, Locator, expect } from '@playwright/test';

export class {{PAGE_CLASS}} {
    readonly page: Page;
{{LOCATOR_PROPERTIES}}
    
    constructor(page: Page) {
        this.page = page;
{{LOCATOR_INITIALIZATIONS}}
    }
    
    async navigate() {
        await this.page.goto('{{PAGE_URL}}');
    }
    
{{PAGE_METHODS}}
}
`;

// ============================================
// COMPONENT TEST TEMPLATE (REACT)
// ============================================

export const REACT_COMPONENT_TEST_TEMPLATE = `/**
 * Component Tests: {{COMPONENT_NAME}}
 * Generated by Test Agent
 */

import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
{{IMPORTS}}

describe('{{COMPONENT_NAME}}', () => {
    const defaultProps = {
{{DEFAULT_PROPS}}
    };
    
    const renderComponent = (props = {}) => {
        return render(<{{COMPONENT_NAME}} {...defaultProps} {...props} />);
    };
    
{{TEST_CASES}}
});
`;

export const COMPONENT_TEST_CASE_TEMPLATE = `    it('{{TEST_DESCRIPTION}}', async () => {
        const user = userEvent.setup();
        renderComponent({{PROPS}});
        
        {{ASSERTIONS}}
    });
`;

// ============================================
// SNAPSHOT TEST TEMPLATE
// ============================================

export const SNAPSHOT_TEST_TEMPLATE = `/**
 * Snapshot Tests: {{COMPONENT_NAME}}
 * Generated by Test Agent
 */

import { describe, it, expect } from 'vitest';
import { render } from '@testing-library/react';
{{IMPORTS}}

describe('{{COMPONENT_NAME}} Snapshots', () => {
    it('should match default snapshot', () => {
        const { container } = render(<{{COMPONENT_NAME}} {{DEFAULT_PROPS}} />);
        expect(container).toMatchSnapshot();
    });
    
{{VARIANT_SNAPSHOTS}}
});
`;

// ============================================
// TEST SETUP FILE TEMPLATE
// ============================================

export const TEST_SETUP_TEMPLATE = `/**
 * Test Setup
 * Global test configuration and utilities
 */

import { beforeAll, afterAll, afterEach } from 'vitest';
{{IMPORTS}}

// ============================================
// GLOBAL SETUP
// ============================================

beforeAll(async () => {
    {{BEFORE_ALL}}
});

afterAll(async () => {
    {{AFTER_ALL}}
});

afterEach(() => {
    {{AFTER_EACH}}
});

// ============================================
// CUSTOM MATCHERS
// ============================================

expect.extend({
    toBeWithinRange(received: number, floor: number, ceiling: number) {
        const pass = received >= floor && received <= ceiling;
        return {
            pass,
            message: () =>
                pass
                    ? \`expected \${received} not to be within range \${floor} - \${ceiling}\`
                    : \`expected \${received} to be within range \${floor} - \${ceiling}\`,
        };
    },
});

// ============================================
// TEST UTILITIES
// ============================================

export const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export const createMockResponse = <T>(data: T, status = 200) => ({
    ok: status >= 200 && status < 300,
    status,
    json: async () => data,
    text: async () => JSON.stringify(data),
});

{{ADDITIONAL_UTILITIES}}
`;

// ============================================
// DATABASE TEST UTILITIES TEMPLATE
// ============================================

export const DATABASE_TEST_UTILS_TEMPLATE = `/**
 * Database Test Utilities
 * Generated by Test Agent
 */

import { beforeEach, afterEach, afterAll } from 'vitest';
{{DATABASE_IMPORTS}}

// Test database connection
let testDb: {{DATABASE_TYPE}};

export const setupTestDatabase = async () => {
    {{DB_SETUP}}
    return testDb;
};

export const cleanupTestDatabase = async () => {
    {{DB_CLEANUP}}
};

export const resetTestDatabase = async () => {
    {{DB_RESET}}
};

// Seed test data
export const seedTestData = async (data: Record<string, unknown[]>) => {
    {{DB_SEED}}
};

// Transaction wrapper for test isolation
export const withTransaction = async <T>(
    fn: (trx: {{TRANSACTION_TYPE}}) => Promise<T>
): Promise<T> => {
    {{TRANSACTION_WRAPPER}}
};
`;

// ============================================
// PERFORMANCE TEST TEMPLATE
// ============================================

export const PERFORMANCE_TEST_TEMPLATE = `/**
 * Performance Tests: {{MODULE_NAME}}
 * Generated by Test Agent
 */

import { describe, it, expect, beforeEach } from 'vitest';
{{IMPORTS}}

describe('{{MODULE_NAME}} Performance', () => {
    const ITERATIONS = {{ITERATIONS}};
    const TIMEOUT_MS = {{TIMEOUT_MS}};
    
    it('should complete operation within acceptable time', async () => {
        const start = performance.now();
        
        {{OPERATION}}
        
        const duration = performance.now() - start;
        expect(duration).toBeLessThan(TIMEOUT_MS);
    });
    
    it('should handle {{ITERATIONS}} iterations efficiently', async () => {
        const durations: number[] = [];
        
        for (let i = 0; i < ITERATIONS; i++) {
            const start = performance.now();
            {{OPERATION}}
            durations.push(performance.now() - start);
        }
        
        const average = durations.reduce((a, b) => a + b, 0) / durations.length;
        const max = Math.max(...durations);
        const p95 = durations.sort((a, b) => a - b)[Math.floor(ITERATIONS * 0.95)];
        
        console.log(\`Performance: avg=\${average.toFixed(2)}ms, max=\${max.toFixed(2)}ms, p95=\${p95.toFixed(2)}ms\`);
        
        expect(average).toBeLessThan({{AVG_THRESHOLD}});
        expect(p95).toBeLessThan({{P95_THRESHOLD}});
    });
    
    it('should not have memory leaks', async () => {
        const initialMemory = process.memoryUsage().heapUsed;
        
        for (let i = 0; i < ITERATIONS; i++) {
            {{OPERATION}}
        }
        
        // Force garbage collection if available
        if (global.gc) global.gc();
        
        const finalMemory = process.memoryUsage().heapUsed;
        const memoryGrowth = (finalMemory - initialMemory) / 1024 / 1024; // MB
        
        expect(memoryGrowth).toBeLessThan({{MEMORY_THRESHOLD_MB}});
    });
});
`;

// ============================================
// ACCESSIBILITY TEST TEMPLATE (PLAYWRIGHT + AXE)
// ============================================

export const ACCESSIBILITY_TEST_TEMPLATE = `/**
 * Accessibility Tests: {{PAGE_NAME}}
 * Generated by Test Agent using axe-core
 */

import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test.describe('{{PAGE_NAME}} Accessibility', () => {
    test.beforeEach(async ({ page }) => {
        await page.goto('{{PAGE_URL}}');
    });
    
    test('should have no detectable accessibility issues', async ({ page }) => {
        const accessibilityScanResults = await new AxeBuilder({ page })
            .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
            .analyze();
        
        expect(accessibilityScanResults.violations).toEqual([]);
    });
    
    test('should have no critical accessibility issues', async ({ page }) => {
        const results = await new AxeBuilder({ page })
            .withTags(['wcag2a', 'wcag2aa'])
            .options({ resultTypes: ['violations'] })
            .analyze();
        
        const criticalViolations = results.violations.filter(v => 
            v.impact === 'critical' || v.impact === 'serious'
        );
        
        if (criticalViolations.length > 0) {
            console.log('Critical A11Y violations:', JSON.stringify(criticalViolations, null, 2));
        }
        
        expect(criticalViolations).toHaveLength(0);
    });
    
    test('should have proper keyboard navigation', async ({ page }) => {
        const focusableElements = await page.locator(
            'a, button, input, select, textarea, [tabindex]:not([tabindex="-1"])'
        ).all();
        
        for (const element of focusableElements) {
            await element.focus();
            const isFocused = await element.evaluate(el => document.activeElement === el);
            expect(isFocused).toBe(true);
        }
    });
    
    test('should have proper heading hierarchy', async ({ page }) => {
        const headings = await page.evaluate(() => {
            return Array.from(document.querySelectorAll('h1, h2, h3, h4, h5, h6'))
                .map(h => ({ tag: h.tagName, text: h.textContent?.trim() }));
        });
        
        // Check for single h1
        const h1Count = headings.filter(h => h.tag === 'H1').length;
        expect(h1Count).toBe(1);
        
        // Check heading order
        let lastLevel = 0;
        for (const heading of headings) {
            const level = parseInt(heading.tag.substring(1));
            expect(level).toBeLessThanOrEqual(lastLevel + 1);
            lastLevel = level;
        }
    });
    
    test('should have proper alt text for images', async ({ page }) => {
        const images = await page.locator('img').all();
        
        for (const img of images) {
            const alt = await img.getAttribute('alt');
            const role = await img.getAttribute('role');
            
            // Images should have alt text or role="presentation"
            expect(alt !== null || role === 'presentation').toBe(true);
        }
    });
    
    test('should have proper form labels', async ({ page }) => {
        const inputs = await page.locator('input, select, textarea').all();
        
        for (const input of inputs) {
            const id = await input.getAttribute('id');
            const ariaLabel = await input.getAttribute('aria-label');
            const ariaLabelledBy = await input.getAttribute('aria-labelledby');
            
            if (id) {
                const label = await page.locator(\`label[for="\${id}"]\`).count();
                const hasLabel = label > 0 || ariaLabel || ariaLabelledBy;
                expect(hasLabel).toBe(true);
            }
        }
    });
});
`;

// ============================================
// VISUAL REGRESSION TEST TEMPLATE
// ============================================

export const VISUAL_REGRESSION_TEMPLATE = `/**
 * Visual Regression Tests: {{PAGE_NAME}}
 * Generated by Test Agent
 */

import { test, expect } from '@playwright/test';

test.describe('{{PAGE_NAME}} Visual Regression', () => {
    test.beforeEach(async ({ page }) => {
        await page.goto('{{PAGE_URL}}');
        // Wait for page to be fully loaded
        await page.waitForLoadState('networkidle');
    });
    
    test('full page screenshot matches baseline', async ({ page }) => {
        await expect(page).toHaveScreenshot('{{PAGE_NAME}}-full.png', {
            fullPage: true,
            animations: 'disabled',
        });
    });
    
{{COMPONENT_SCREENSHOTS}}
    
    test('page layout on mobile viewport', async ({ page }) => {
        await page.setViewportSize({ width: 375, height: 667 });
        await expect(page).toHaveScreenshot('{{PAGE_NAME}}-mobile.png', {
            animations: 'disabled',
        });
    });
    
    test('page layout on tablet viewport', async ({ page }) => {
        await page.setViewportSize({ width: 768, height: 1024 });
        await expect(page).toHaveScreenshot('{{PAGE_NAME}}-tablet.png', {
            animations: 'disabled',
        });
    });
    
    test('page layout in dark mode', async ({ page }) => {
        await page.emulateMedia({ colorScheme: 'dark' });
        await expect(page).toHaveScreenshot('{{PAGE_NAME}}-dark.png', {
            animations: 'disabled',
        });
    });
});
`;

// ============================================
// COVERAGE REPORT TEMPLATE
// ============================================

export const COVERAGE_REPORT_TEMPLATE = `/**
 * Coverage Report Configuration
 * Generated by Test Agent
 */

export const coverageConfig = {
    enabled: true,
    provider: '{{COVERAGE_PROVIDER}}',
    reporters: ['text', 'json', 'html', 'lcov'],
    reportsDirectory: './coverage',
    
    // Thresholds
    thresholds: {
        statements: {{STMT_THRESHOLD}},
        branches: {{BRANCH_THRESHOLD}},
        functions: {{FUNC_THRESHOLD}},
        lines: {{LINES_THRESHOLD}},
    },
    
    // Exclusions
    exclude: [
        'node_modules/**',
        'dist/**',
        'coverage/**',
        '**/*.d.ts',
        '**/*.test.{ts,js}',
        '**/*.spec.{ts,js}',
        'test/**',
        '__tests__/**',
        '**/__mocks__/**',
    ],
    
    // File inclusion
    include: [
        'src/**/*.{ts,js}',
    ],
    
    // Per-file thresholds
    perFile: {{PER_FILE_THRESHOLDS}},
};

/**
 * Generate coverage badge
 */
export function getCoverageBadge(percentage: number): string {
    let color = 'red';
    if (percentage >= 80) color = 'brightgreen';
    else if (percentage >= 60) color = 'yellow';
    else if (percentage >= 40) color = 'orange';
    
    return \`![Coverage](https://img.shields.io/badge/coverage-\${percentage}%25-\${color})\`;
}

/**
 * Coverage summary type
 */
export interface CoverageSummary {
    statements: { covered: number; total: number; pct: number };
    branches: { covered: number; total: number; pct: number };
    functions: { covered: number; total: number; pct: number };
    lines: { covered: number; total: number; pct: number };
}

/**
 * Check if coverage meets thresholds
 */
export function checkThresholds(summary: CoverageSummary): { pass: boolean; failures: string[] } {
    const failures: string[] = [];
    
    if (summary.statements.pct < {{STMT_THRESHOLD}}) {
        failures.push(\`Statements: \${summary.statements.pct}% < \${{{STMT_THRESHOLD}}}%\`);
    }
    if (summary.branches.pct < {{BRANCH_THRESHOLD}}) {
        failures.push(\`Branches: \${summary.branches.pct}% < \${{{BRANCH_THRESHOLD}}}%\`);
    }
    if (summary.functions.pct < {{FUNC_THRESHOLD}}) {
        failures.push(\`Functions: \${summary.functions.pct}% < \${{{FUNC_THRESHOLD}}}%\`);
    }
    if (summary.lines.pct < {{LINES_THRESHOLD}}) {
        failures.push(\`Lines: \${summary.lines.pct}% < \${{{LINES_THRESHOLD}}}%\`);
    }
    
    return { pass: failures.length === 0, failures };
}
`;

// ============================================
// LOAD TEST TEMPLATE
// ============================================

export const LOAD_TEST_TEMPLATE = `/**
 * Load Tests: {{API_NAME}}
 * Generated by Test Agent
 */

import { describe, it, expect } from 'vitest';
{{IMPORTS}}

describe('{{API_NAME}} Load Testing', () => {
    const CONCURRENT_USERS = {{CONCURRENT_USERS}};
    const REQUESTS_PER_USER = {{REQUESTS_PER_USER}};
    const TARGET_RPS = {{TARGET_RPS}};
    
    it('should handle concurrent requests', async () => {
        const startTime = Date.now();
        
        // Create concurrent users
        const userPromises = Array.from({ length: CONCURRENT_USERS }, async (_, userId) => {
            const results: { success: boolean; duration: number }[] = [];
            
            for (let i = 0; i < REQUESTS_PER_USER; i++) {
                const reqStart = Date.now();
                try {
                    {{REQUEST_CODE}}
                    results.push({ success: true, duration: Date.now() - reqStart });
                } catch (error) {
                    results.push({ success: false, duration: Date.now() - reqStart });
                }
            }
            
            return results;
        });
        
        const allResults = (await Promise.all(userPromises)).flat();
        const totalDuration = Date.now() - startTime;
        
        // Calculate stats
        const successCount = allResults.filter(r => r.success).length;
        const successRate = (successCount / allResults.length) * 100;
        const totalRequests = allResults.length;
        const avgDuration = allResults.reduce((sum, r) => sum + r.duration, 0) / allResults.length;
        const rps = (totalRequests / totalDuration) * 1000;
        
        console.log(\`Load Test Results:
            Total Requests: \${totalRequests}
            Success Rate: \${successRate.toFixed(2)}%
            Average Response Time: \${avgDuration.toFixed(2)}ms
            Requests/Second: \${rps.toFixed(2)}
            Total Duration: \${totalDuration}ms
        \`);
        
        expect(successRate).toBeGreaterThanOrEqual({{SUCCESS_RATE_THRESHOLD}});
        expect(avgDuration).toBeLessThan({{AVG_RESPONSE_THRESHOLD}});
    });
});
`;

// ============================================
// HELPER EXPORTS
// ============================================

export const ALL_TEMPLATES = {
    // Config templates
    VITEST_CONFIG_TEMPLATE,
    JEST_CONFIG_TEMPLATE,
    PLAYWRIGHT_CONFIG_TEMPLATE,

    // Unit test templates
    UNIT_TEST_TEMPLATE,
    TEST_CASE_TEMPLATE,
    EDGE_CASE_TEMPLATE,

    // Mock templates
    MOCK_FILE_TEMPLATE,
    MOCK_FUNCTION_TEMPLATE,
    MOCK_ASYNC_FUNCTION_TEMPLATE,

    // Fixture templates
    FIXTURE_FILE_TEMPLATE,
    FACTORY_FUNCTION_TEMPLATE,

    // Integration test templates
    INTEGRATION_TEST_TEMPLATE,
    INTEGRATION_TEST_CASE_TEMPLATE,

    // API test templates
    API_TEST_TEMPLATE,
    API_TEST_CASE_TEMPLATE,

    // E2E test templates
    E2E_TEST_TEMPLATE,
    E2E_TEST_CASE_TEMPLATE,
    E2E_STEP_TEMPLATES,
    BROWSER_PROJECT_TEMPLATE,
    PAGE_OBJECT_TEMPLATE,

    // Component test templates
    REACT_COMPONENT_TEST_TEMPLATE,
    COMPONENT_TEST_CASE_TEMPLATE,
    SNAPSHOT_TEST_TEMPLATE,

    // Setup templates
    TEST_SETUP_TEMPLATE,
    DATABASE_TEST_UTILS_TEMPLATE,

    // Advanced test templates
    PERFORMANCE_TEST_TEMPLATE,
    ACCESSIBILITY_TEST_TEMPLATE,
    VISUAL_REGRESSION_TEMPLATE,
    COVERAGE_REPORT_TEMPLATE,
    LOAD_TEST_TEMPLATE,
};

