/**
 * Route Generator Service
 * 
 * Phase 17.1: Generate Functional Routes
 * 
 * Generates actual working API routes:
 * - Auth routes (login, register, refresh, logout)
 * - Security middleware wiring
 * - Full CRUD endpoints for entities
 */

export interface RouteConfig {
    basePath: string;
    framework: 'fastify' | 'express' | 'hono';
    authentication: 'jwt' | 'session' | 'none';
    validation: 'zod' | 'ajv' | 'none';
    database: 'prisma' | 'supabase' | 'drizzle';
}

export interface EntityRoute {
    name: string;
    path: string;
    fields: Array<{
        name: string;
        type: string;
        required?: boolean;
        unique?: boolean;
    }>;
    authentication?: boolean;
    softDelete?: boolean;
}

export interface GeneratedRoute {
    path: string;
    content: string;
    type: 'route' | 'middleware' | 'schema' | 'controller';
}

export interface RouteGenerationResult {
    files: GeneratedRoute[];
    dependencies: string[];
}

// ============================================
// ROUTE GENERATOR
// ============================================

export class RouteGenerator {
    private config: RouteConfig;

    constructor(config?: Partial<RouteConfig>) {
        this.config = {
            basePath: '/api/v1',
            framework: config?.framework || 'fastify',
            authentication: config?.authentication || 'jwt',
            validation: config?.validation || 'zod',
            database: config?.database || 'prisma',
        };
    }

    /**
     * Generate all routes for given entities
     */
    generateAll(entities: EntityRoute[]): RouteGenerationResult {
        const files: GeneratedRoute[] = [];
        const dependencies: string[] = [];

        console.log(`[ROUTE-GENERATOR] Generating routes for ${entities.length} entities`);

        // Generate auth routes
        const authResult = this.generateAuthRoutes();
        files.push(...authResult.files);
        dependencies.push(...authResult.dependencies);

        // Generate security middleware
        const securityResult = this.generateSecurityMiddleware();
        files.push(...securityResult.files);
        dependencies.push(...securityResult.dependencies);

        // Generate CRUD routes for each entity
        for (const entity of entities) {
            const crudResult = this.generateCrudRoutes(entity);
            files.push(...crudResult.files);
            dependencies.push(...crudResult.dependencies);
        }

        // Generate main route aggregator
        files.push(this.generateRouteIndex(entities));

        // Deduplicate dependencies
        const uniqueDeps = Array.from(new Set(dependencies));

        console.log(`[ROUTE-GENERATOR] Generated ${files.length} files`);

        return { files, dependencies: uniqueDeps };
    }

    // ============================================
    // AUTH ROUTES
    // ============================================

    generateAuthRoutes(): RouteGenerationResult {
        const files: GeneratedRoute[] = [];
        const dependencies: string[] = ['jsonwebtoken', 'bcryptjs'];

        if (this.config.validation === 'zod') {
            dependencies.push('zod');
        }

        // Auth schemas
        files.push({
            path: 'src/auth/schemas.ts',
            content: this.generateAuthSchemas(),
            type: 'schema',
        });

        // Auth service
        files.push({
            path: 'src/auth/auth.service.ts',
            content: this.generateAuthService(),
            type: 'controller',
        });

        // Auth routes
        files.push({
            path: 'src/auth/auth.routes.ts',
            content: this.generateAuthRoutesFile(),
            type: 'route',
        });

        // Auth middleware
        files.push({
            path: 'src/auth/auth.middleware.ts',
            content: this.generateAuthMiddleware(),
            type: 'middleware',
        });

        return { files, dependencies };
    }

    private generateAuthSchemas(): string {
        return `/**
 * Auth Validation Schemas
 * Generated by Loveable Backend Orchestrator
 */

import { z } from 'zod';

export const registerSchema = z.object({
    email: z.string().email('Invalid email address'),
    password: z.string().min(8, 'Password must be at least 8 characters'),
    username: z.string().min(3, 'Username must be at least 3 characters').optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional(),
});

export const loginSchema = z.object({
    email: z.string().email('Invalid email address'),
    password: z.string().min(1, 'Password is required'),
});

export const refreshTokenSchema = z.object({
    refreshToken: z.string().min(1, 'Refresh token is required'),
});

export const changePasswordSchema = z.object({
    currentPassword: z.string().min(1, 'Current password is required'),
    newPassword: z.string().min(8, 'New password must be at least 8 characters'),
});

export const forgotPasswordSchema = z.object({
    email: z.string().email('Invalid email address'),
});

export const resetPasswordSchema = z.object({
    token: z.string().min(1, 'Reset token is required'),
    newPassword: z.string().min(8, 'New password must be at least 8 characters'),
});

// Type exports
export type RegisterInput = z.infer<typeof registerSchema>;
export type LoginInput = z.infer<typeof loginSchema>;
export type RefreshTokenInput = z.infer<typeof refreshTokenSchema>;
export type ChangePasswordInput = z.infer<typeof changePasswordSchema>;
export type ForgotPasswordInput = z.infer<typeof forgotPasswordSchema>;
export type ResetPasswordInput = z.infer<typeof resetPasswordSchema>;
`;
    }

    private generateAuthService(): string {
        const dbImport = this.config.database === 'prisma'
            ? "import { prisma } from '../lib/prisma';"
            : "import { supabaseAdmin } from '../lib/supabase';";

        return `/**
 * Auth Service
 * Generated by Loveable Backend Orchestrator
 */

import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
${dbImport}
import type { RegisterInput, LoginInput } from './schemas';

const JWT_SECRET = process.env.JWT_SECRET || 'your-secret-key';
const JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN || '15m';
const JWT_REFRESH_EXPIRES_IN = process.env.JWT_REFRESH_EXPIRES_IN || '7d';
const BCRYPT_ROUNDS = parseInt(process.env.BCRYPT_ROUNDS || '12', 10);

export interface TokenPayload {
    userId: string;
    email: string;
    type: 'access' | 'refresh';
}

export interface AuthTokens {
    accessToken: string;
    refreshToken: string;
    expiresIn: number;
}

export interface UserResponse {
    id: string;
    email: string;
    username?: string;
    firstName?: string;
    lastName?: string;
    createdAt: Date;
}

export class AuthService {
    /**
     * Register a new user
     */
    async register(data: RegisterInput): Promise<{ user: UserResponse; tokens: AuthTokens }> {
        // Hash password
        const hashedPassword = await bcrypt.hash(data.password, BCRYPT_ROUNDS);

        ${this.config.database === 'prisma' ? `
        // Check if user exists
        const existingUser = await prisma.user.findUnique({
            where: { email: data.email },
        });

        if (existingUser) {
            throw new Error('User with this email already exists');
        }

        // Create user
        const user = await prisma.user.create({
            data: {
                email: data.email,
                password: hashedPassword,
                username: data.username,
                firstName: data.firstName,
                lastName: data.lastName,
            },
        });` : `
        // Check if user exists
        const { data: existingUser } = await supabaseAdmin
            .from('users')
            .select('id')
            .eq('email', data.email)
            .single();

        if (existingUser) {
            throw new Error('User with this email already exists');
        }

        // Create user
        const { data: user, error } = await supabaseAdmin
            .from('users')
            .insert({
                email: data.email,
                password: hashedPassword,
                username: data.username,
                first_name: data.firstName,
                last_name: data.lastName,
            })
            .select()
            .single();

        if (error) throw error;`}

        // Generate tokens
        const tokens = this.generateTokens(user.id, user.email);

        return {
            user: this.sanitizeUser(user),
            tokens,
        };
    }

    /**
     * Login user
     */
    async login(data: LoginInput): Promise<{ user: UserResponse; tokens: AuthTokens }> {
        ${this.config.database === 'prisma' ? `
        // Find user
        const user = await prisma.user.findUnique({
            where: { email: data.email },
        });` : `
        // Find user
        const { data: user, error } = await supabaseAdmin
            .from('users')
            .select('*')
            .eq('email', data.email)
            .single();

        if (error && error.code !== 'PGRST116') throw error;`}

        if (!user) {
            throw new Error('Invalid email or password');
        }

        // Verify password
        const isValid = await bcrypt.compare(data.password, user.password);
        if (!isValid) {
            throw new Error('Invalid email or password');
        }

        // Generate tokens
        const tokens = this.generateTokens(user.id, user.email);

        return {
            user: this.sanitizeUser(user),
            tokens,
        };
    }

    /**
     * Refresh access token
     */
    async refreshToken(refreshToken: string): Promise<AuthTokens> {
        try {
            const decoded = jwt.verify(refreshToken, JWT_SECRET) as TokenPayload;

            if (decoded.type !== 'refresh') {
                throw new Error('Invalid token type');
            }

            ${this.config.database === 'prisma' ? `
            // Verify user still exists
            const user = await prisma.user.findUnique({
                where: { id: decoded.userId },
            });` : `
            // Verify user still exists
            const { data: user } = await supabaseAdmin
                .from('users')
                .select('id, email')
                .eq('id', decoded.userId)
                .single();`}

            if (!user) {
                throw new Error('User not found');
            }

            return this.generateTokens(user.id, user.email);
        } catch (error) {
            throw new Error('Invalid or expired refresh token');
        }
    }

    /**
     * Get current user
     */
    async getCurrentUser(userId: string): Promise<UserResponse> {
        ${this.config.database === 'prisma' ? `
        const user = await prisma.user.findUnique({
            where: { id: userId },
        });` : `
        const { data: user, error } = await supabaseAdmin
            .from('users')
            .select('*')
            .eq('id', userId)
            .single();

        if (error) throw error;`}

        if (!user) {
            throw new Error('User not found');
        }

        return this.sanitizeUser(user);
    }

    /**
     * Verify access token
     */
    verifyToken(token: string): TokenPayload {
        try {
            const decoded = jwt.verify(token, JWT_SECRET) as TokenPayload;
            if (decoded.type !== 'access') {
                throw new Error('Invalid token type');
            }
            return decoded;
        } catch (error) {
            throw new Error('Invalid or expired token');
        }
    }

    /**
     * Generate access and refresh tokens
     */
    private generateTokens(userId: string, email: string): AuthTokens {
        const accessToken = jwt.sign(
            { userId, email, type: 'access' } as TokenPayload,
            JWT_SECRET,
            { expiresIn: JWT_EXPIRES_IN }
        );

        const refreshToken = jwt.sign(
            { userId, email, type: 'refresh' } as TokenPayload,
            JWT_SECRET,
            { expiresIn: JWT_REFRESH_EXPIRES_IN }
        );

        // Parse expiry (simple version, assumes 'm' for minutes)
        const expiresIn = parseInt(JWT_EXPIRES_IN.replace(/[^0-9]/g, ''), 10) * 60;

        return { accessToken, refreshToken, expiresIn };
    }

    /**
     * Remove sensitive fields from user object
     */
    private sanitizeUser(user: Record<string, unknown>): UserResponse {
        return {
            id: user.id as string,
            email: user.email as string,
            username: user.username as string | undefined,
            firstName: (user.firstName || user.first_name) as string | undefined,
            lastName: (user.lastName || user.last_name) as string | undefined,
            createdAt: new Date(user.createdAt as string || user.created_at as string),
        };
    }
}

// Singleton
export const authService = new AuthService();
`;
    }

    private generateAuthRoutesFile(): string {
        if (this.config.framework === 'fastify') {
            return this.generateFastifyAuthRoutes();
        }
        return this.generateExpressAuthRoutes();
    }

    private generateFastifyAuthRoutes(): string {
        return `/**
 * Auth Routes - Fastify
 * Generated by Loveable Backend Orchestrator
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { authService } from './auth.service';
import { authMiddleware } from './auth.middleware';
import {
    registerSchema,
    loginSchema,
    refreshTokenSchema,
    type RegisterInput,
    type LoginInput,
    type RefreshTokenInput,
} from './schemas';

export async function authRoutes(app: FastifyInstance): Promise<void> {
    /**
     * POST /auth/register
     * Register a new user
     */
    app.post('/auth/register', async (
        request: FastifyRequest<{ Body: RegisterInput }>,
        reply: FastifyReply
    ) => {
        try {
            // Validate input
            const validated = registerSchema.parse(request.body);

            const result = await authService.register(validated);

            return reply.status(201).send({
                success: true,
                data: result,
            });
        } catch (error) {
            const message = error instanceof Error ? error.message : 'Registration failed';
            return reply.status(400).send({
                success: false,
                error: message,
            });
        }
    });

    /**
     * POST /auth/login
     * Login user
     */
    app.post('/auth/login', async (
        request: FastifyRequest<{ Body: LoginInput }>,
        reply: FastifyReply
    ) => {
        try {
            // Validate input
            const validated = loginSchema.parse(request.body);

            const result = await authService.login(validated);

            return reply.send({
                success: true,
                data: result,
            });
        } catch (error) {
            const message = error instanceof Error ? error.message : 'Login failed';
            return reply.status(401).send({
                success: false,
                error: message,
            });
        }
    });

    /**
     * POST /auth/refresh
     * Refresh access token
     */
    app.post('/auth/refresh', async (
        request: FastifyRequest<{ Body: RefreshTokenInput }>,
        reply: FastifyReply
    ) => {
        try {
            const validated = refreshTokenSchema.parse(request.body);

            const tokens = await authService.refreshToken(validated.refreshToken);

            return reply.send({
                success: true,
                data: tokens,
            });
        } catch (error) {
            const message = error instanceof Error ? error.message : 'Token refresh failed';
            return reply.status(401).send({
                success: false,
                error: message,
            });
        }
    });

    /**
     * GET /auth/me
     * Get current user (protected)
     */
    app.get('/auth/me', {
        preHandler: authMiddleware,
    }, async (
        request: FastifyRequest,
        reply: FastifyReply
    ) => {
        try {
            const userId = (request as FastifyRequest & { userId: string }).userId;
            const user = await authService.getCurrentUser(userId);

            return reply.send({
                success: true,
                data: user,
            });
        } catch (error) {
            const message = error instanceof Error ? error.message : 'Failed to get user';
            return reply.status(401).send({
                success: false,
                error: message,
            });
        }
    });

    /**
     * POST /auth/logout
     * Logout user (client should clear tokens)
     */
    app.post('/auth/logout', {
        preHandler: authMiddleware,
    }, async (
        _request: FastifyRequest,
        reply: FastifyReply
    ) => {
        // JWT is stateless - client should clear tokens
        // For server-side token invalidation, implement a token blacklist
        return reply.send({
            success: true,
            message: 'Logged out successfully',
        });
    });

    app.log.info('✅ Auth routes registered');
}
`;
    }

    private generateExpressAuthRoutes(): string {
        return `/**
 * Auth Routes - Express
 * Generated by Loveable Backend Orchestrator
 */

import { Router, Request, Response, NextFunction } from 'express';
import { authService } from './auth.service';
import { authMiddleware } from './auth.middleware';
import {
    registerSchema,
    loginSchema,
    refreshTokenSchema,
} from './schemas';

const router = Router();

/**
 * POST /auth/register
 */
router.post('/register', async (req: Request, res: Response, next: NextFunction) => {
    try {
        const validated = registerSchema.parse(req.body);
        const result = await authService.register(validated);
        res.status(201).json({ success: true, data: result });
    } catch (error) {
        next(error);
    }
});

/**
 * POST /auth/login
 */
router.post('/login', async (req: Request, res: Response, next: NextFunction) => {
    try {
        const validated = loginSchema.parse(req.body);
        const result = await authService.login(validated);
        res.json({ success: true, data: result });
    } catch (error) {
        next(error);
    }
});

/**
 * POST /auth/refresh
 */
router.post('/refresh', async (req: Request, res: Response, next: NextFunction) => {
    try {
        const validated = refreshTokenSchema.parse(req.body);
        const tokens = await authService.refreshToken(validated.refreshToken);
        res.json({ success: true, data: tokens });
    } catch (error) {
        next(error);
    }
});

/**
 * GET /auth/me
 */
router.get('/me', authMiddleware, async (req: Request, res: Response, next: NextFunction) => {
    try {
        const userId = (req as Request & { userId: string }).userId;
        const user = await authService.getCurrentUser(userId);
        res.json({ success: true, data: user });
    } catch (error) {
        next(error);
    }
});

/**
 * POST /auth/logout
 */
router.post('/logout', authMiddleware, async (_req: Request, res: Response) => {
    res.json({ success: true, message: 'Logged out successfully' });
});

export { router as authRoutes };
`;
    }

    private generateAuthMiddleware(): string {
        if (this.config.framework === 'fastify') {
            return `/**
 * Auth Middleware - Fastify
 * Generated by Loveable Backend Orchestrator
 */

import { FastifyRequest, FastifyReply } from 'fastify';
import { authService } from './auth.service';

export async function authMiddleware(
    request: FastifyRequest,
    reply: FastifyReply
): Promise<void> {
    try {
        const authHeader = request.headers.authorization;

        if (!authHeader || !authHeader.startsWith('Bearer ')) {
            return reply.status(401).send({
                success: false,
                error: 'Missing or invalid authorization header',
            });
        }

        const token = authHeader.substring(7);
        const decoded = authService.verifyToken(token);

        // Attach user info to request
        (request as FastifyRequest & { userId: string; userEmail: string }).userId = decoded.userId;
        (request as FastifyRequest & { userId: string; userEmail: string }).userEmail = decoded.email;
    } catch (error) {
        return reply.status(401).send({
            success: false,
            error: 'Invalid or expired token',
        });
    }
}

/**
 * Optional auth middleware - doesn't fail if no token
 */
export async function optionalAuthMiddleware(
    request: FastifyRequest,
    _reply: FastifyReply
): Promise<void> {
    try {
        const authHeader = request.headers.authorization;

        if (authHeader && authHeader.startsWith('Bearer ')) {
            const token = authHeader.substring(7);
            const decoded = authService.verifyToken(token);
            (request as FastifyRequest & { userId: string; userEmail: string }).userId = decoded.userId;
            (request as FastifyRequest & { userId: string; userEmail: string }).userEmail = decoded.email;
        }
    } catch {
        // Ignore errors for optional auth
    }
}
`;
        }

        return `/**
 * Auth Middleware - Express
 * Generated by Loveable Backend Orchestrator
 */

import { Request, Response, NextFunction } from 'express';
import { authService } from './auth.service';

export function authMiddleware(
    req: Request,
    res: Response,
    next: NextFunction
): void {
    try {
        const authHeader = req.headers.authorization;

        if (!authHeader || !authHeader.startsWith('Bearer ')) {
            res.status(401).json({
                success: false,
                error: 'Missing or invalid authorization header',
            });
            return;
        }

        const token = authHeader.substring(7);
        const decoded = authService.verifyToken(token);

        (req as Request & { userId: string; userEmail: string }).userId = decoded.userId;
        (req as Request & { userId: string; userEmail: string }).userEmail = decoded.email;

        next();
    } catch (error) {
        res.status(401).json({
            success: false,
            error: 'Invalid or expired token',
        });
    }
}

export function optionalAuthMiddleware(
    req: Request,
    _res: Response,
    next: NextFunction
): void {
    try {
        const authHeader = req.headers.authorization;

        if (authHeader && authHeader.startsWith('Bearer ')) {
            const token = authHeader.substring(7);
            const decoded = authService.verifyToken(token);
            (req as Request & { userId: string; userEmail: string }).userId = decoded.userId;
            (req as Request & { userId: string; userEmail: string }).userEmail = decoded.email;
        }
    } catch {
        // Ignore
    }
    next();
}
`;
    }

    // ============================================
    // SECURITY MIDDLEWARE
    // ============================================

    generateSecurityMiddleware(): RouteGenerationResult {
        const files: GeneratedRoute[] = [];
        const dependencies: string[] = [];

        if (this.config.framework === 'fastify') {
            dependencies.push('@fastify/helmet', '@fastify/cors', '@fastify/rate-limit');
        } else {
            dependencies.push('helmet', 'cors', 'express-rate-limit');
        }

        files.push({
            path: 'src/middleware/security.ts',
            content: this.generateSecurityMiddlewareFile(),
            type: 'middleware',
        });

        files.push({
            path: 'src/middleware/error-handler.ts',
            content: this.generateErrorHandler(),
            type: 'middleware',
        });

        files.push({
            path: 'src/middleware/request-logger.ts',
            content: this.generateRequestLogger(),
            type: 'middleware',
        });

        return { files, dependencies };
    }

    private generateSecurityMiddlewareFile(): string {
        if (this.config.framework === 'fastify') {
            return `/**
 * Security Middleware - Fastify
 * Generated by Loveable Backend Orchestrator
 */

import { FastifyInstance } from 'fastify';
import helmet from '@fastify/helmet';
import cors from '@fastify/cors';
import rateLimit from '@fastify/rate-limit';

export async function registerSecurityMiddleware(app: FastifyInstance): Promise<void> {
    // Helmet - Security headers
    await app.register(helmet, {
        contentSecurityPolicy: {
            directives: {
                defaultSrc: ["'self'"],
                scriptSrc: ["'self'"],
                styleSrc: ["'self'", "'unsafe-inline'"],
                imgSrc: ["'self'", 'data:', 'https:'],
            },
        },
    });

    // CORS
    await app.register(cors, {
        origin: process.env.CORS_ORIGIN?.split(',') || ['http://localhost:3000'],
        credentials: true,
        methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
        allowedHeaders: ['Content-Type', 'Authorization', 'X-Request-ID'],
    });

    // Rate Limiting
    await app.register(rateLimit, {
        max: parseInt(process.env.RATE_LIMIT_MAX || '100', 10),
        timeWindow: parseInt(process.env.RATE_LIMIT_WINDOW_MS || '60000', 10),
        errorResponseBuilder: () => ({
            success: false,
            error: 'Too many requests, please try again later',
            statusCode: 429,
        }),
    });

    app.log.info('✅ Security middleware registered');
}
`;
        }

        return `/**
 * Security Middleware - Express
 * Generated by Loveable Backend Orchestrator
 */

import { Application } from 'express';
import helmet from 'helmet';
import cors from 'cors';
import rateLimit from 'express-rate-limit';

export function registerSecurityMiddleware(app: Application): void {
    // Helmet
    app.use(helmet());

    // CORS
    app.use(cors({
        origin: process.env.CORS_ORIGIN?.split(',') || ['http://localhost:3000'],
        credentials: true,
        methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
    }));

    // Rate Limiting
    app.use(rateLimit({
        max: parseInt(process.env.RATE_LIMIT_MAX || '100', 10),
        windowMs: parseInt(process.env.RATE_LIMIT_WINDOW_MS || '60000', 10),
        message: { success: false, error: 'Too many requests' },
    }));

    console.log('✅ Security middleware registered');
}
`;
    }

    private generateErrorHandler(): string {
        if (this.config.framework === 'fastify') {
            return `/**
 * Error Handler - Fastify
 * Generated by Loveable Backend Orchestrator
 */

import { FastifyInstance, FastifyError, FastifyRequest, FastifyReply } from 'fastify';
import { ZodError } from 'zod';

export function registerErrorHandler(app: FastifyInstance): void {
    app.setErrorHandler((error: FastifyError, request: FastifyRequest, reply: FastifyReply) => {
        request.log.error(error);

        // Zod validation errors
        if (error instanceof ZodError) {
            return reply.status(400).send({
                success: false,
                error: 'Validation failed',
                details: error.errors.map(e => ({
                    field: e.path.join('.'),
                    message: e.message,
                })),
            });
        }

        // Known errors
        if (error.statusCode) {
            return reply.status(error.statusCode).send({
                success: false,
                error: error.message,
            });
        }

        // Unknown errors
        const statusCode = 500;
        const message = process.env.NODE_ENV === 'production'
            ? 'Internal server error'
            : error.message;

        return reply.status(statusCode).send({
            success: false,
            error: message,
        });
    });

    app.log.info('✅ Error handler registered');
}
`;
        }

        return `/**
 * Error Handler - Express
 * Generated by Loveable Backend Orchestrator
 */

import { Request, Response, NextFunction } from 'express';
import { ZodError } from 'zod';

export function errorHandler(
    error: Error,
    _req: Request,
    res: Response,
    _next: NextFunction
): void {
    console.error(error);

    if (error instanceof ZodError) {
        res.status(400).json({
            success: false,
            error: 'Validation failed',
            details: error.errors,
        });
        return;
    }

    const statusCode = 500;
    const message = process.env.NODE_ENV === 'production'
        ? 'Internal server error'
        : error.message;

    res.status(statusCode).json({ success: false, error: message });
}
`;
    }

    private generateRequestLogger(): string {
        return `/**
 * Request Logger Middleware
 * Generated by Loveable Backend Orchestrator
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';

export function registerRequestLogger(app: FastifyInstance): void {
    app.addHook('onRequest', async (request: FastifyRequest, _reply: FastifyReply) => {
        request.log.info({
            method: request.method,
            url: request.url,
            ip: request.ip,
            userAgent: request.headers['user-agent'],
        }, 'Incoming request');
    });

    app.addHook('onResponse', async (request: FastifyRequest, reply: FastifyReply) => {
        request.log.info({
            method: request.method,
            url: request.url,
            statusCode: reply.statusCode,
            responseTime: reply.elapsedTime,
        }, 'Request completed');
    });

    app.log.info('✅ Request logger registered');
}
`;
    }

    // ============================================
    // CRUD ROUTES
    // ============================================

    generateCrudRoutes(entity: EntityRoute): RouteGenerationResult {
        const files: GeneratedRoute[] = [];
        const dependencies: string[] = [];

        // Entity schemas
        files.push({
            path: `src/${this.toKebabCase(entity.name)}/schemas.ts`,
            content: this.generateEntitySchemas(entity),
            type: 'schema',
        });

        // Entity routes
        files.push({
            path: `src/${this.toKebabCase(entity.name)}/${this.toKebabCase(entity.name)}.routes.ts`,
            content: this.generateEntityRoutes(entity),
            type: 'route',
        });

        return { files, dependencies };
    }

    private generateEntitySchemas(entity: EntityRoute): string {
        const fields = entity.fields.map(f => {
            let zodType = 'z.string()';
            switch (f.type) {
                case 'int':
                case 'float':
                case 'number':
                    zodType = 'z.number()';
                    break;
                case 'boolean':
                    zodType = 'z.boolean()';
                    break;
                case 'date':
                case 'datetime':
                    zodType = 'z.string().datetime()';
                    break;
                case 'email':
                    zodType = 'z.string().email()';
                    break;
                default:
                    zodType = 'z.string()';
            }

            if (!f.required) {
                zodType += '.optional()';
            }

            return `    ${f.name}: ${zodType},`;
        }).join('\n');

        const updateFields = entity.fields.map(f => {
            let zodType = 'z.string()';
            switch (f.type) {
                case 'int':
                case 'float':
                case 'number':
                    zodType = 'z.number()';
                    break;
                case 'boolean':
                    zodType = 'z.boolean()';
                    break;
                default:
                    zodType = 'z.string()';
            }
            return `    ${f.name}: ${zodType}.optional(),`;
        }).join('\n');

        return `/**
 * ${entity.name} Schemas
 * Generated by Loveable Backend Orchestrator
 */

import { z } from 'zod';

export const create${entity.name}Schema = z.object({
${fields}
});

export const update${entity.name}Schema = z.object({
${updateFields}
});

export const query${entity.name}Schema = z.object({
    page: z.coerce.number().min(1).default(1),
    limit: z.coerce.number().min(1).max(100).default(20),
    sortBy: z.string().optional(),
    sortOrder: z.enum(['asc', 'desc']).optional(),
    search: z.string().optional(),
});

export type Create${entity.name}Input = z.infer<typeof create${entity.name}Schema>;
export type Update${entity.name}Input = z.infer<typeof update${entity.name}Schema>;
export type Query${entity.name}Input = z.infer<typeof query${entity.name}Schema>;
`;
    }

    private generateEntityRoutes(entity: EntityRoute): string {
        const name = entity.name;
        const varName = name.charAt(0).toLowerCase() + name.slice(1);
        const kebabName = this.toKebabCase(name);
        const authHook = entity.authentication ? 'preHandler: authMiddleware,' : '';

        return `/**
 * ${name} Routes
 * Generated by Loveable Backend Orchestrator
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
${entity.authentication ? "import { authMiddleware } from '../auth/auth.middleware';" : ''}
import { ${varName}Service } from '../services/${kebabName}.service';
import {
    create${name}Schema,
    update${name}Schema,
    query${name}Schema,
    type Create${name}Input,
    type Update${name}Input,
    type Query${name}Input,
} from './schemas';

export async function ${varName}Routes(app: FastifyInstance): Promise<void> {
    /**
     * GET /${entity.path}
     * List all ${varName}s with pagination
     */
    app.get('/${entity.path}', {
        ${authHook}
    }, async (
        request: FastifyRequest<{ Querystring: Query${name}Input }>,
        reply: FastifyReply
    ) => {
        try {
            const query = query${name}Schema.parse(request.query);
            const result = await ${varName}Service.findAll(query);

            return reply.send({
                success: true,
                data: result.data,
                pagination: {
                    page: result.page,
                    limit: result.limit,
                    total: result.total,
                    totalPages: Math.ceil(result.total / result.limit),
                },
            });
        } catch (error) {
            const message = error instanceof Error ? error.message : 'Failed to fetch ${varName}s';
            return reply.status(500).send({ success: false, error: message });
        }
    });

    /**
     * GET /${entity.path}/:id
     * Get single ${varName} by ID
     */
    app.get('/${entity.path}/:id', {
        ${authHook}
    }, async (
        request: FastifyRequest<{ Params: { id: string } }>,
        reply: FastifyReply
    ) => {
        try {
            const { id } = request.params;
            const ${varName} = await ${varName}Service.findById(id);

            if (!${varName}) {
                return reply.status(404).send({
                    success: false,
                    error: '${name} not found',
                });
            }

            return reply.send({ success: true, data: ${varName} });
        } catch (error) {
            const message = error instanceof Error ? error.message : 'Failed to fetch ${varName}';
            return reply.status(500).send({ success: false, error: message });
        }
    });

    /**
     * POST /${entity.path}
     * Create new ${varName}
     */
    app.post('/${entity.path}', {
        ${authHook}
    }, async (
        request: FastifyRequest<{ Body: Create${name}Input }>,
        reply: FastifyReply
    ) => {
        try {
            const data = create${name}Schema.parse(request.body);
            const ${varName} = await ${varName}Service.create(data);

            return reply.status(201).send({ success: true, data: ${varName} });
        } catch (error) {
            const message = error instanceof Error ? error.message : 'Failed to create ${varName}';
            return reply.status(400).send({ success: false, error: message });
        }
    });

    /**
     * PUT /${entity.path}/:id
     * Update ${varName}
     */
    app.put('/${entity.path}/:id', {
        ${authHook}
    }, async (
        request: FastifyRequest<{ Params: { id: string }; Body: Update${name}Input }>,
        reply: FastifyReply
    ) => {
        try {
            const { id } = request.params;
            const data = update${name}Schema.parse(request.body);

            // Check if exists
            const exists = await ${varName}Service.exists(id);
            if (!exists) {
                return reply.status(404).send({
                    success: false,
                    error: '${name} not found',
                });
            }

            const ${varName} = await ${varName}Service.update(id, data);
            return reply.send({ success: true, data: ${varName} });
        } catch (error) {
            const message = error instanceof Error ? error.message : 'Failed to update ${varName}';
            return reply.status(400).send({ success: false, error: message });
        }
    });

    /**
     * DELETE /${entity.path}/:id
     * Delete ${varName}
     */
    app.delete('/${entity.path}/:id', {
        ${authHook}
    }, async (
        request: FastifyRequest<{ Params: { id: string } }>,
        reply: FastifyReply
    ) => {
        try {
            const { id } = request.params;

            const exists = await ${varName}Service.exists(id);
            if (!exists) {
                return reply.status(404).send({
                    success: false,
                    error: '${name} not found',
                });
            }

            await ${varName}Service.delete(id);
            return reply.send({ success: true, message: '${name} deleted successfully' });
        } catch (error) {
            const message = error instanceof Error ? error.message : 'Failed to delete ${varName}';
            return reply.status(500).send({ success: false, error: message });
        }
    });

    app.log.info('✅ ${name} routes registered at /${entity.path}');
}
`;
    }

    // ============================================
    // ROUTE INDEX
    // ============================================

    private generateRouteIndex(entities: EntityRoute[]): GeneratedRoute {
        const imports: string[] = [];
        const registrations: string[] = [];

        imports.push("import { authRoutes } from './auth/auth.routes';");
        registrations.push("await app.register(authRoutes, { prefix: '/api/v1' });");

        for (const entity of entities) {
            const varName = entity.name.charAt(0).toLowerCase() + entity.name.slice(1);
            const kebabName = this.toKebabCase(entity.name);
            imports.push(`import { ${varName}Routes } from './${kebabName}/${kebabName}.routes';`);
            registrations.push(`await app.register(${varName}Routes, { prefix: '/api/v1' });`);
        }

        const content = `/**
 * Route Index
 * Generated by Loveable Backend Orchestrator
 */

import { FastifyInstance } from 'fastify';
${imports.join('\n')}

export async function registerRoutes(app: FastifyInstance): Promise<void> {
    // Health check
    app.get('/health', async () => ({
        status: 'ok',
        timestamp: new Date().toISOString(),
    }));

    // Register API routes
${registrations.map(r => `    ${r}`).join('\n')}

    app.log.info('✅ All routes registered');
}
`;

        return {
            path: 'src/routes/index.ts',
            content,
            type: 'route',
        };
    }

    // ============================================
    // UTILITIES
    // ============================================

    private toKebabCase(str: string): string {
        return str.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`).replace(/^-/, '');
    }
}

// ============================================
// FACTORY FUNCTIONS
// ============================================

let routeGeneratorInstance: RouteGenerator | null = null;

export function getRouteGenerator(): RouteGenerator {
    if (!routeGeneratorInstance) {
        routeGeneratorInstance = new RouteGenerator();
    }
    return routeGeneratorInstance;
}

export function createRouteGenerator(config?: Partial<RouteConfig>): RouteGenerator {
    routeGeneratorInstance = new RouteGenerator(config);
    return routeGeneratorInstance;
}
