/**
 * Project Routes
 * Project management endpoints
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { z } from 'zod';
import { authenticate, getAuthUser } from '../middleware/auth-middleware.js';
import type { AuthenticatedUser } from '../middleware/auth-middleware.js';
import AdmZip from 'adm-zip';

// Extend FastifyRequest type for authenticated routes
declare module 'fastify' {
    interface FastifyRequest {
        authUser?: AuthenticatedUser;
    }
}

// Validation schemas
const createProjectSchema = z.object({
    name: z.string().min(1, 'Project name is required').max(100),
    description: z.string().max(500).optional(),
    config: z.record(z.unknown()).optional(),
});

const updateProjectSchema = z.object({
    name: z.string().min(1).max(100).optional(),
    description: z.string().max(500).optional(),
    config: z.record(z.unknown()).optional(),
});

const listProjectsQuerySchema = z.object({
    status: z.enum(['pending', 'generating', 'completed', 'failed']).optional(),
    limit: z.coerce.number().min(1).max(100).default(20),
    offset: z.coerce.number().min(0).default(0),
});

// Type definitions
type CreateProjectBody = z.infer<typeof createProjectSchema>;
type UpdateProjectBody = z.infer<typeof updateProjectSchema>;
type ListProjectsQuery = z.infer<typeof listProjectsQuerySchema>;

/**
 * Generate a ZIP file from project files
 */
async function generateProjectZip(files: Array<{ path: string; content: string }>): Promise<Buffer> {
    const zip = new AdmZip();

    // Add each file to the ZIP
    for (const file of files) {
        // Normalize path to ensure it uses forward slashes
        const normalizedPath = file.path.replace(/\\/g, '/');

        // Add file to ZIP
        zip.addFile(normalizedPath, Buffer.from(file.content, 'utf-8'));
    }

    // Generate ZIP buffer
    return zip.toBuffer();
}

/**
 * Create a sample project structure for demonstration
 */
function createSampleProjectFiles(projectId: string): Array<{ path: string; content: string }> {
    return [
        {
            path: 'README.md',
            content: `# Project ${projectId}\n\nThis project was generated by Loveable Backend.\n\nGenerated at: ${new Date().toISOString()}\n`,
        },
        {
            path: 'package.json',
            content: JSON.stringify({
                name: `project-${projectId}`,
                version: '1.0.0',
                description: 'Generated project',
                main: 'index.js',
                scripts: {
                    start: 'node index.js',
                    test: 'echo "Error: no test specified" && exit 1',
                },
            }, null, 2),
        },
        {
            path: 'src/index.js',
            content: `// Main entry point for project ${projectId}\n\nconsole.log('Hello from project ${projectId}!');\n`,
        },
        {
            path: '.gitignore',
            content: 'node_modules/\n.env\ndist/\n*.log\n',
        },
    ];
}

/**
 * Register project routes
 */
export async function registerProjectRoutes(app: FastifyInstance): Promise<void> {

    /**
     * POST /api/v1/projects - Create project
     */
    app.post('/api/v1/projects', {
        preHandler: authenticate({ required: true }),
        schema: {
            tags: ['Projects'],
            summary: 'Create new project',
            security: [{ bearerAuth: [] }],
            body: {
                type: 'object',
                required: ['name'],
                properties: {
                    name: { type: 'string', minLength: 1, maxLength: 100 },
                    description: { type: 'string', maxLength: 500 },
                    config: { type: 'object' },
                },
            },
            response: {
                201: {
                    type: 'object',
                    properties: {
                        id: { type: 'string' },
                        name: { type: 'string' },
                        description: { type: 'string' },
                        status: { type: 'string' },
                        createdAt: { type: 'string' },
                    },
                },
            },
        },
    }, async (request: FastifyRequest<{ Body: CreateProjectBody }>, reply: FastifyReply) => {
        const validation = createProjectSchema.safeParse(request.body);

        if (!validation.success) {
            return reply.status(400).send({
                error: 'Validation failed',
                details: validation.error.flatten(),
            });
        }

        // Get authenticated user
        const user = request.authUser;
        if (!user) {
            return reply.status(401).send({
                error: 'Authentication required',
            });
        }

        const { name, description, config } = validation.data;

        // TODO: Create project in database with user.id
        // const project = await projectsService.create({ user_id: user.id, name, description, config });

        // Placeholder response
        const projectId = `proj_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

        return reply.status(201).send({
            id: projectId,
            name,
            description: description || null,
            config: config || {},
            status: 'pending',
            createdAt: new Date().toISOString(),
        });
    });

    /**
     * GET /api/v1/projects - List user's projects
     */
    app.get('/api/v1/projects', {
        preHandler: authenticate({ required: true }),
        schema: {
            tags: ['Projects'],
            summary: 'List user projects',
            security: [{ bearerAuth: [] }],
            querystring: {
                type: 'object',
                properties: {
                    status: { type: 'string', enum: ['pending', 'generating', 'completed', 'failed'] },
                    limit: { type: 'number', default: 20, minimum: 1, maximum: 100 },
                    offset: { type: 'number', default: 0, minimum: 0 },
                },
            },
            response: {
                200: {
                    type: 'object',
                    properties: {
                        projects: {
                            type: 'array',
                            items: {
                                type: 'object',
                                properties: {
                                    id: { type: 'string' },
                                    name: { type: 'string' },
                                    description: { type: 'string' },
                                    status: { type: 'string' },
                                    createdAt: { type: 'string' },
                                    updatedAt: { type: 'string' },
                                },
                            },
                        },
                        total: { type: 'number' },
                        limit: { type: 'number' },
                        offset: { type: 'number' },
                    },
                },
            },
        },
    }, async (request: FastifyRequest<{ Querystring: ListProjectsQuery }>, reply: FastifyReply) => {
        const validation = listProjectsQuerySchema.safeParse(request.query);

        if (!validation.success) {
            return reply.status(400).send({
                error: 'Invalid query parameters',
                details: validation.error.flatten(),
            });
        }

        const { limit, offset } = validation.data;
        const user = request.authUser;

        // Authenticated via preHandler
        // TODO: Get projects from database
        // const { projects, total } = await projectsService.getByUserId(user.id, { status, limit, offset });

        return reply.send({
            projects: [],
            total: 0,
            limit,
            offset,
        });
    });

    /**
     * GET /api/v1/projects/:id - Get project details
     */
    app.get('/api/v1/projects/:id', {
        preHandler: authenticate({ required: true }),
        schema: {
            tags: ['Projects'],
            summary: 'Get project details',
            security: [{ bearerAuth: [] }],
            params: {
                type: 'object',
                properties: {
                    id: { type: 'string' },
                },
                required: ['id'],
            },
            response: {
                200: {
                    type: 'object',
                    properties: {
                        id: { type: 'string' },
                        name: { type: 'string' },
                        description: { type: 'string' },
                        config: { type: 'object' },
                        status: { type: 'string' },
                        tasks: { type: 'array' },
                        createdAt: { type: 'string' },
                        updatedAt: { type: 'string' },
                    },
                },
                404: {
                    type: 'object',
                    properties: {
                        error: { type: 'string' },
                    },
                },
            },
        },
    }, async (request: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
        const { id } = request.params;
        const user = request.authUser;

        // Authenticated via preHandler
        // TODO: Get project from database
        // const project = await projectsService.getById(id);

        return reply.status(404).send({
            error: `Project ${id} not found`,
        });
    });

    /**
     * PUT /api/v1/projects/:id - Update project
     */
    app.put('/api/v1/projects/:id', {
        preHandler: authenticate({ required: true }),
        schema: {
            tags: ['Projects'],
            summary: 'Update project',
            security: [{ bearerAuth: [] }],
            params: {
                type: 'object',
                properties: {
                    id: { type: 'string' },
                },
                required: ['id'],
            },
            body: {
                type: 'object',
                properties: {
                    name: { type: 'string', minLength: 1, maxLength: 100 },
                    description: { type: 'string', maxLength: 500 },
                    config: { type: 'object' },
                },
            },
            response: {
                200: {
                    type: 'object',
                    properties: {
                        id: { type: 'string' },
                        name: { type: 'string' },
                        description: { type: 'string' },
                        status: { type: 'string' },
                        updatedAt: { type: 'string' },
                    },
                },
            },
        },
    }, async (request: FastifyRequest<{ Params: { id: string }; Body: UpdateProjectBody }>, reply: FastifyReply) => {
        const { id } = request.params;

        const validation = updateProjectSchema.safeParse(request.body);

        if (!validation.success) {
            return reply.status(400).send({
                error: 'Validation failed',
                details: validation.error.flatten(),
            });
        }

        const user = request.authUser;

        // Authenticated via preHandler
        // TODO: Update project in database
        // const project = await projectsService.update(id, validation.data);

        return reply.status(404).send({
            error: `Project ${id} not found`,
        });
    });

    /**
     * DELETE /api/v1/projects/:id - Delete project
     */
    app.delete('/api/v1/projects/:id', {
        preHandler: authenticate({ required: true }),
        schema: {
            tags: ['Projects'],
            summary: 'Delete project',
            security: [{ bearerAuth: [] }],
            params: {
                type: 'object',
                properties: {
                    id: { type: 'string' },
                },
                required: ['id'],
            },
            response: {
                200: {
                    type: 'object',
                    properties: {
                        success: { type: 'boolean' },
                        message: { type: 'string' },
                    },
                },
            },
        },
    }, async (request: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
        const { id } = request.params;
        const user = request.authUser;

        // Authenticated via preHandler
        // TODO: Delete project from database
        // await projectsService.delete(id);

        return reply.send({
            success: true,
            message: `Project ${id} deleted`,
        });
    });

    /**
     * GET /api/v1/projects/:id/download - Download generated code as ZIP
     */
    app.get('/api/v1/projects/:id/download', {
        preHandler: authenticate({ required: true }),
        schema: {
            tags: ['Projects'],
            summary: 'Download project as ZIP',
            security: [{ bearerAuth: [] }],
            params: {
                type: 'object',
                properties: {
                    id: { type: 'string' },
                },
                required: ['id'],
            },
        },
    }, async (request: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
        const { id } = request.params;
        const user = request.authUser;

        // Authenticated via preHandler
        // TODO: Check project ownership when database is available
        // const project = await projectsService.getById(id);
        // if (project.userId !== user.id) {
        //     return reply.status(403).send({ error: 'Access denied' });
        // }

        try {
            // For now, generate sample project files
            // In production, fetch files from database based on project ID
            const projectFiles = createSampleProjectFiles(id);

            app.log.info({ projectId: id, fileCount: projectFiles.length }, 'Generating ZIP file');

            // Generate ZIP buffer
            const zipBuffer = await generateProjectZip(projectFiles);

            // Set appropriate headers for ZIP download
            reply.header('Content-Type', 'application/zip');
            reply.header('Content-Disposition', `attachment; filename="project-${id}.zip"`);
            reply.header('Content-Length', zipBuffer.length);

            // Send ZIP buffer
            return reply.send(zipBuffer);

        } catch (error) {
            app.log.error(error, 'Failed to generate ZIP file');

            return reply.status(500).send({
                error: 'Failed to generate ZIP file',
                message: error instanceof Error ? error.message : 'Unknown error',
            });
        }
    });

    app.log.info('[ROUTES] Project routes registered: /api/v1/projects/*');
}
